// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: agent.capnp

package io.github.foohq.foojank;

public final class Agent {
  public static final org.capnproto.Text.Reader CMD_START_WORKER_T = new org.capnproto.Text.Reader(Schemas.b_9506b02397c7c539.buffer, 25, 31);
  public static final org.capnproto.Text.Reader CMD_STOP_WORKER_T = new org.capnproto.Text.Reader(Schemas.b_dcc6193d77e90e4f.buffer, 25, 30);
  public static final org.capnproto.Text.Reader CMD_WRITE_STDIN_T = new org.capnproto.Text.Reader(Schemas.b_bdc379322dc88999.buffer, 25, 31);
  public static final org.capnproto.Text.Reader EVT_START_WORKER_T = new org.capnproto.Text.Reader(Schemas.b_8bde75b9b9344aed.buffer, 25, 31);
  public static final org.capnproto.Text.Reader EVT_STOP_WORKER_T = new org.capnproto.Text.Reader(Schemas.b_af4e3d88746f93bc.buffer, 25, 30);
  public static final org.capnproto.Text.Reader EVT_WORKER_STATUS_T = new org.capnproto.Text.Reader(Schemas.b_ee62811487468816.buffer, 25, 32);
  public static final org.capnproto.Text.Reader EVT_WORKER_STDOUT_T = new org.capnproto.Text.Reader(Schemas.b_c795479e88a0bca5.buffer, 25, 32);
  public static final org.capnproto.Text.Reader EVT_AGENT_INFO_T = new org.capnproto.Text.Reader(Schemas.b_913505385db08e95.buffer, 25, 20);
  public static class StartWorkerRequest {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)3);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return StartWorkerRequest.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasCommand() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getCommand() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setCommand(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setCommand(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initCommand(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final boolean hasArgs() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.TextList.Builder getArgs() {
        return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
      }
      public final void setArgs(org.capnproto.TextList.Reader value) {
        _setPointerField(org.capnproto.TextList.factory, 1, value);
      }
      public final org.capnproto.TextList.Builder initArgs(int size) {
        return _initPointerField(org.capnproto.TextList.factory, 1, size);
      }
      public final boolean hasEnv() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.TextList.Builder getEnv() {
        return _getPointerField(org.capnproto.TextList.factory, 2, null, 0);
      }
      public final void setEnv(org.capnproto.TextList.Reader value) {
        _setPointerField(org.capnproto.TextList.factory, 2, value);
      }
      public final org.capnproto.TextList.Builder initEnv(int size) {
        return _initPointerField(org.capnproto.TextList.factory, 2, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasCommand() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getCommand() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public final boolean hasArgs() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.TextList.Reader getArgs() {
        return _getPointerField(org.capnproto.TextList.factory, 1, null, 0);
      }

      public final boolean hasEnv() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.TextList.Reader getEnv() {
        return _getPointerField(org.capnproto.TextList.factory, 2, null, 0);
      }

    }

  }


  public static class StartWorkerResponse {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return StartWorkerResponse.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasError() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setError(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setError(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initError(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasError() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

    }

  }


  public static class StopWorkerRequest {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)0);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return StopWorkerRequest.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

    }

  }


  public static class StopWorkerResponse {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return StopWorkerResponse.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasError() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setError(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setError(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initError(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasError() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getError() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

    }

  }


  public static class UpdateWorkerStatus {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)0);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return UpdateWorkerStatus.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final long getStatus() {
        return _getLongField(0);
      }
      public final void setStatus(long value) {
        _setLongField(0, value);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public final long getStatus() {
        return _getLongField(0);
      }

    }

  }


  public static class UpdateWorkerStdio {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return UpdateWorkerStdio.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasData() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Data.Builder getData() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }
      public final void setData(org.capnproto.Data.Reader value) {
        _setPointerField(org.capnproto.Data.factory, 0, value);
      }
      public final void setData(byte [] value) {
        _setPointerField(org.capnproto.Data.factory, 0, new org.capnproto.Data.Reader(value));
      }
      public final org.capnproto.Data.Builder initData(int size) {
        return _initPointerField(org.capnproto.Data.factory, 0, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasData() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Data.Reader getData() {
        return _getPointerField(org.capnproto.Data.factory, 0, null, 0, 0);
      }

    }

  }


  public static class UpdateClientInfo {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)0,(short)4);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return UpdateClientInfo.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final boolean hasUsername() {
        return !_pointerFieldIsNull(0);
      }
      public final org.capnproto.Text.Builder getUsername() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }
      public final void setUsername(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 0, value);
      }
      public final void setUsername(String value) {
        _setPointerField(org.capnproto.Text.factory, 0, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initUsername(int size) {
        return _initPointerField(org.capnproto.Text.factory, 0, size);
      }
      public final boolean hasHostname() {
        return !_pointerFieldIsNull(1);
      }
      public final org.capnproto.Text.Builder getHostname() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }
      public final void setHostname(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 1, value);
      }
      public final void setHostname(String value) {
        _setPointerField(org.capnproto.Text.factory, 1, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initHostname(int size) {
        return _initPointerField(org.capnproto.Text.factory, 1, size);
      }
      public final boolean hasSystem() {
        return !_pointerFieldIsNull(2);
      }
      public final org.capnproto.Text.Builder getSystem() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }
      public final void setSystem(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 2, value);
      }
      public final void setSystem(String value) {
        _setPointerField(org.capnproto.Text.factory, 2, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initSystem(int size) {
        return _initPointerField(org.capnproto.Text.factory, 2, size);
      }
      public final boolean hasAddress() {
        return !_pointerFieldIsNull(3);
      }
      public final org.capnproto.Text.Builder getAddress() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }
      public final void setAddress(org.capnproto.Text.Reader value) {
        _setPointerField(org.capnproto.Text.factory, 3, value);
      }
      public final void setAddress(String value) {
        _setPointerField(org.capnproto.Text.factory, 3, new org.capnproto.Text.Reader(value));
      }
      public final org.capnproto.Text.Builder initAddress(int size) {
        return _initPointerField(org.capnproto.Text.factory, 3, size);
      }
    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public boolean hasUsername() {
        return !_pointerFieldIsNull(0);
      }
      public org.capnproto.Text.Reader getUsername() {
        return _getPointerField(org.capnproto.Text.factory, 0, null, 0, 0);
      }

      public boolean hasHostname() {
        return !_pointerFieldIsNull(1);
      }
      public org.capnproto.Text.Reader getHostname() {
        return _getPointerField(org.capnproto.Text.factory, 1, null, 0, 0);
      }

      public boolean hasSystem() {
        return !_pointerFieldIsNull(2);
      }
      public org.capnproto.Text.Reader getSystem() {
        return _getPointerField(org.capnproto.Text.factory, 2, null, 0, 0);
      }

      public boolean hasAddress() {
        return !_pointerFieldIsNull(3);
      }
      public org.capnproto.Text.Reader getAddress() {
        return _getPointerField(org.capnproto.Text.factory, 3, null, 0, 0);
      }

    }

  }


  public static class Message {
    public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
    public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
      public Factory() {
      }
      public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
        return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
      }
      public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
        return new Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final org.capnproto.StructSize structSize() {
        return Message.STRUCT_SIZE;
      }
      public final Reader asReader(Builder builder) {
        return builder.asReader();
      }
    }
    public static final Factory factory = new Factory();
    public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
      new org.capnproto.StructList.Factory<Builder, Reader>(factory);
    public static final class Builder extends org.capnproto.StructBuilder {
      Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
        super(segment, data, pointers, dataSize, pointerCount);
      }
      public final Reader asReader() {
        return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
      }
      public final Content.Builder getContent() {
        return new Message.Content.Builder(segment, data, pointers, dataSize, pointerCount);
      }
      public final Content.Builder initContent() {
        _setShortField(0,(short)0);
        _clearPointerField(0);
  return new Message.Content.Builder(segment, data, pointers, dataSize, pointerCount);
      }

    }

    public static final class Reader extends org.capnproto.StructReader {
      Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
        super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

      public Content.Reader getContent() {
        return new Message.Content.Reader(segment, data, pointers, dataSize, pointerCount, nestingLimit);
      }

    }

    public static class Content {
      public static final org.capnproto.StructSize STRUCT_SIZE = new org.capnproto.StructSize((short)1,(short)1);
      public static final class Factory extends org.capnproto.StructFactory<Builder, Reader> {
        public Factory() {
        }
        public final Reader constructReader(org.capnproto.SegmentReader segment, int data,int pointers, int dataSize, short pointerCount, int nestingLimit) {
          return new Reader(segment,data,pointers,dataSize,pointerCount,nestingLimit);
        }
        public final Builder constructBuilder(org.capnproto.SegmentBuilder segment, int data,int pointers, int dataSize, short pointerCount) {
          return new Builder(segment, data, pointers, dataSize, pointerCount);
        }
        public final org.capnproto.StructSize structSize() {
          return Message.Content.STRUCT_SIZE;
        }
        public final Reader asReader(Builder builder) {
          return builder.asReader();
        }
      }
      public static final Factory factory = new Factory();
      public static final org.capnproto.StructList.Factory<Builder,Reader> listFactory =
        new org.capnproto.StructList.Factory<Builder, Reader>(factory);
      public static final class Builder extends org.capnproto.StructBuilder {
        Builder(org.capnproto.SegmentBuilder segment, int data, int pointers,int dataSize, short pointerCount){
          super(segment, data, pointers, dataSize, pointerCount);
        }
        public Which which() {
          switch(_getShortField(0)) {
            case 0 : return Which.START_WORKER_REQUEST;
            case 1 : return Which.START_WORKER_RESPONSE;
            case 2 : return Which.STOP_WORKER_REQUEST;
            case 3 : return Which.STOP_WORKER_RESPONSE;
            case 4 : return Which.UPDATE_WORKER_STATUS;
            case 5 : return Which.UPDATE_WORKER_STDIO;
            case 6 : return Which.UPDATE_CLIENT_INFO;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final Reader asReader() {
          return new Reader(segment, data, pointers, dataSize, pointerCount, 0x7fffffff);
        }
        public final boolean isStartWorkerRequest() {
          return which() == Message.Content.Which.START_WORKER_REQUEST;
        }
        public final io.github.foohq.foojank.Agent.StartWorkerRequest.Builder getStartWorkerRequest() {
          assert which() == Message.Content.Which.START_WORKER_REQUEST:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StartWorkerRequest.factory, 0, null, 0);
        }
        public final void setStartWorkerRequest(io.github.foohq.foojank.Agent.StartWorkerRequest.Reader value) {
          _setShortField(0, (short)Message.Content.Which.START_WORKER_REQUEST.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.StartWorkerRequest.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.StartWorkerRequest.Builder initStartWorkerRequest() {
          _setShortField(0, (short)Message.Content.Which.START_WORKER_REQUEST.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.StartWorkerRequest.factory,0, 0);
        }
        public final boolean isStartWorkerResponse() {
          return which() == Message.Content.Which.START_WORKER_RESPONSE;
        }
        public final io.github.foohq.foojank.Agent.StartWorkerResponse.Builder getStartWorkerResponse() {
          assert which() == Message.Content.Which.START_WORKER_RESPONSE:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StartWorkerResponse.factory, 0, null, 0);
        }
        public final void setStartWorkerResponse(io.github.foohq.foojank.Agent.StartWorkerResponse.Reader value) {
          _setShortField(0, (short)Message.Content.Which.START_WORKER_RESPONSE.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.StartWorkerResponse.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.StartWorkerResponse.Builder initStartWorkerResponse() {
          _setShortField(0, (short)Message.Content.Which.START_WORKER_RESPONSE.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.StartWorkerResponse.factory,0, 0);
        }
        public final boolean isStopWorkerRequest() {
          return which() == Message.Content.Which.STOP_WORKER_REQUEST;
        }
        public final io.github.foohq.foojank.Agent.StopWorkerRequest.Builder getStopWorkerRequest() {
          assert which() == Message.Content.Which.STOP_WORKER_REQUEST:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StopWorkerRequest.factory, 0, null, 0);
        }
        public final void setStopWorkerRequest(io.github.foohq.foojank.Agent.StopWorkerRequest.Reader value) {
          _setShortField(0, (short)Message.Content.Which.STOP_WORKER_REQUEST.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.StopWorkerRequest.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.StopWorkerRequest.Builder initStopWorkerRequest() {
          _setShortField(0, (short)Message.Content.Which.STOP_WORKER_REQUEST.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.StopWorkerRequest.factory,0, 0);
        }
        public final boolean isStopWorkerResponse() {
          return which() == Message.Content.Which.STOP_WORKER_RESPONSE;
        }
        public final io.github.foohq.foojank.Agent.StopWorkerResponse.Builder getStopWorkerResponse() {
          assert which() == Message.Content.Which.STOP_WORKER_RESPONSE:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StopWorkerResponse.factory, 0, null, 0);
        }
        public final void setStopWorkerResponse(io.github.foohq.foojank.Agent.StopWorkerResponse.Reader value) {
          _setShortField(0, (short)Message.Content.Which.STOP_WORKER_RESPONSE.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.StopWorkerResponse.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.StopWorkerResponse.Builder initStopWorkerResponse() {
          _setShortField(0, (short)Message.Content.Which.STOP_WORKER_RESPONSE.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.StopWorkerResponse.factory,0, 0);
        }
        public final boolean isUpdateWorkerStatus() {
          return which() == Message.Content.Which.UPDATE_WORKER_STATUS;
        }
        public final io.github.foohq.foojank.Agent.UpdateWorkerStatus.Builder getUpdateWorkerStatus() {
          assert which() == Message.Content.Which.UPDATE_WORKER_STATUS:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStatus.factory, 0, null, 0);
        }
        public final void setUpdateWorkerStatus(io.github.foohq.foojank.Agent.UpdateWorkerStatus.Reader value) {
          _setShortField(0, (short)Message.Content.Which.UPDATE_WORKER_STATUS.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStatus.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.UpdateWorkerStatus.Builder initUpdateWorkerStatus() {
          _setShortField(0, (short)Message.Content.Which.UPDATE_WORKER_STATUS.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStatus.factory,0, 0);
        }
        public final boolean isUpdateWorkerStdio() {
          return which() == Message.Content.Which.UPDATE_WORKER_STDIO;
        }
        public final io.github.foohq.foojank.Agent.UpdateWorkerStdio.Builder getUpdateWorkerStdio() {
          assert which() == Message.Content.Which.UPDATE_WORKER_STDIO:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStdio.factory, 0, null, 0);
        }
        public final void setUpdateWorkerStdio(io.github.foohq.foojank.Agent.UpdateWorkerStdio.Reader value) {
          _setShortField(0, (short)Message.Content.Which.UPDATE_WORKER_STDIO.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStdio.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.UpdateWorkerStdio.Builder initUpdateWorkerStdio() {
          _setShortField(0, (short)Message.Content.Which.UPDATE_WORKER_STDIO.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStdio.factory,0, 0);
        }
        public final boolean isUpdateClientInfo() {
          return which() == Message.Content.Which.UPDATE_CLIENT_INFO;
        }
        public final io.github.foohq.foojank.Agent.UpdateClientInfo.Builder getUpdateClientInfo() {
          assert which() == Message.Content.Which.UPDATE_CLIENT_INFO:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateClientInfo.factory, 0, null, 0);
        }
        public final void setUpdateClientInfo(io.github.foohq.foojank.Agent.UpdateClientInfo.Reader value) {
          _setShortField(0, (short)Message.Content.Which.UPDATE_CLIENT_INFO.ordinal());
          _setPointerField(io.github.foohq.foojank.Agent.UpdateClientInfo.factory,0, value);
        }
        public final io.github.foohq.foojank.Agent.UpdateClientInfo.Builder initUpdateClientInfo() {
          _setShortField(0, (short)Message.Content.Which.UPDATE_CLIENT_INFO.ordinal());
          return _initPointerField(io.github.foohq.foojank.Agent.UpdateClientInfo.factory,0, 0);
        }
      }

      public static final class Reader extends org.capnproto.StructReader {
        Reader(org.capnproto.SegmentReader segment, int data, int pointers,int dataSize, short pointerCount, int nestingLimit){
          super(segment, data, pointers, dataSize, pointerCount, nestingLimit);
        }

        public Which which() {
          switch(_getShortField(0)) {
            case 0 : return Which.START_WORKER_REQUEST;
            case 1 : return Which.START_WORKER_RESPONSE;
            case 2 : return Which.STOP_WORKER_REQUEST;
            case 3 : return Which.STOP_WORKER_RESPONSE;
            case 4 : return Which.UPDATE_WORKER_STATUS;
            case 5 : return Which.UPDATE_WORKER_STDIO;
            case 6 : return Which.UPDATE_CLIENT_INFO;
            default: return Which._NOT_IN_SCHEMA;
          }
        }
        public final boolean isStartWorkerRequest() {
          return which() == Message.Content.Which.START_WORKER_REQUEST;
        }
        public boolean hasStartWorkerRequest() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.StartWorkerRequest.Reader getStartWorkerRequest() {
          assert which() == Message.Content.Which.START_WORKER_REQUEST:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StartWorkerRequest.factory,0,null, 0);
        }

        public final boolean isStartWorkerResponse() {
          return which() == Message.Content.Which.START_WORKER_RESPONSE;
        }
        public boolean hasStartWorkerResponse() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.StartWorkerResponse.Reader getStartWorkerResponse() {
          assert which() == Message.Content.Which.START_WORKER_RESPONSE:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StartWorkerResponse.factory,0,null, 0);
        }

        public final boolean isStopWorkerRequest() {
          return which() == Message.Content.Which.STOP_WORKER_REQUEST;
        }
        public boolean hasStopWorkerRequest() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.StopWorkerRequest.Reader getStopWorkerRequest() {
          assert which() == Message.Content.Which.STOP_WORKER_REQUEST:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StopWorkerRequest.factory,0,null, 0);
        }

        public final boolean isStopWorkerResponse() {
          return which() == Message.Content.Which.STOP_WORKER_RESPONSE;
        }
        public boolean hasStopWorkerResponse() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.StopWorkerResponse.Reader getStopWorkerResponse() {
          assert which() == Message.Content.Which.STOP_WORKER_RESPONSE:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.StopWorkerResponse.factory,0,null, 0);
        }

        public final boolean isUpdateWorkerStatus() {
          return which() == Message.Content.Which.UPDATE_WORKER_STATUS;
        }
        public boolean hasUpdateWorkerStatus() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.UpdateWorkerStatus.Reader getUpdateWorkerStatus() {
          assert which() == Message.Content.Which.UPDATE_WORKER_STATUS:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStatus.factory,0,null, 0);
        }

        public final boolean isUpdateWorkerStdio() {
          return which() == Message.Content.Which.UPDATE_WORKER_STDIO;
        }
        public boolean hasUpdateWorkerStdio() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.UpdateWorkerStdio.Reader getUpdateWorkerStdio() {
          assert which() == Message.Content.Which.UPDATE_WORKER_STDIO:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateWorkerStdio.factory,0,null, 0);
        }

        public final boolean isUpdateClientInfo() {
          return which() == Message.Content.Which.UPDATE_CLIENT_INFO;
        }
        public boolean hasUpdateClientInfo() {
          return !_pointerFieldIsNull(0);
        }
        public io.github.foohq.foojank.Agent.UpdateClientInfo.Reader getUpdateClientInfo() {
          assert which() == Message.Content.Which.UPDATE_CLIENT_INFO:
                      "Must check which() before get()ing a union member.";
          return _getPointerField(io.github.foohq.foojank.Agent.UpdateClientInfo.factory,0,null, 0);
        }

      }

      public enum Which {
        START_WORKER_REQUEST,
        START_WORKER_RESPONSE,
        STOP_WORKER_REQUEST,
        STOP_WORKER_RESPONSE,
        UPDATE_WORKER_STATUS,
        UPDATE_WORKER_STDIO,
        UPDATE_CLIENT_INFO,
        _NOT_IN_SCHEMA,
      }
    }


  }



public static final class Schemas {
public static final org.capnproto.SegmentReader b_9506b02397c7c539 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0039\u00c5\u00c7\u0097\u0023\u00b0\u0006\u0095" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f6\u0000\u0000\u0000\u0037\u0001\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00e2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0063\u006d\u0064\u0053" +
   "\u0074\u0061\u0072\u0074\u0057\u006f\u0072\u006b" +
   "\u0065\u0072\u0054\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0002\u0001\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0043\u004d\u0044\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u0041\u0052\u0054\u0000" + "");
public static final org.capnproto.SegmentReader b_dcc6193d77e90e4f =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u004f\u000e\u00e9\u0077\u003d\u0019\u00c6\u00dc" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0038\u0001\u0000\u0000\u0078\u0001\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0063\u006d\u0064\u0053" +
   "\u0074\u006f\u0070\u0057\u006f\u0072\u006b\u0065" +
   "\u0072\u0054\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0043\u004d\u0044\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u004f\u0050\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_bdc379322dc88999 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0099\u0089\u00c8\u002d\u0032\u0079\u00c3\u00bd" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0079\u0001\u0000\u0000\u00ba\u0001\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0063\u006d\u0064\u0057" +
   "\u0072\u0069\u0074\u0065\u0053\u0074\u0064\u0069" +
   "\u006e\u0054\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0002\u0001\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0043\u004d\u0044\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u0044\u0049\u004e\u0000" + "");
public static final org.capnproto.SegmentReader b_8bde75b9b9344aed =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00ed\u004a\u0034\u00b9\u00b9\u0075\u00de\u008b" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00bc\u0001\u0000\u0000\u00fd\u0001\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00e2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0065\u0076\u0074\u0053" +
   "\u0074\u0061\u0072\u0074\u0057\u006f\u0072\u006b" +
   "\u0065\u0072\u0054\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0002\u0001\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0045\u0056\u0054\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u0041\u0052\u0054\u0000" + "");
public static final org.capnproto.SegmentReader b_af4e3d88746f93bc =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00bc\u0093\u006f\u0074\u0088\u003d\u004e\u00af" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00fe\u0001\u0000\u0000\u003e\u0002\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00da\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0065\u0076\u0074\u0053" +
   "\u0074\u006f\u0070\u0057\u006f\u0072\u006b\u0065" +
   "\u0072\u0054\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0045\u0056\u0054\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u004f\u0050\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_ee62811487468816 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0016\u0088\u0046\u0087\u0014\u0081\u0062\u00ee" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u003f\u0002\u0000\u0000\u0081\u0002\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ea\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0065\u0076\u0074\u0057" +
   "\u006f\u0072\u006b\u0065\u0072\u0053\u0074\u0061" +
   "\u0074\u0075\u0073\u0054\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\n\u0001\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0045\u0056\u0054\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u0041\u0054\u0055\u0053" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_c795479e88a0bca5 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00a5\u00bc\u00a0\u0088\u009e\u0047\u0095\u00c7" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0082\u0002\u0000\u0000\u00c4\u0002\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ea\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0065\u0076\u0074\u0057" +
   "\u006f\u0072\u006b\u0065\u0072\u0053\u0074\u0064" +
   "\u006f\u0075\u0074\u0054\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\n\u0001\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0045\u0056\u0054\u002e" +
   "\u0057\u004f\u0052\u004b\u0045\u0052\u002e\u0025" +
   "\u0073\u002e\u0053\u0054\u0044\u004f\u0055\u0054" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_913505385db08e95 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0095\u008e\u00b0\u005d\u0038\u0005\u0035\u0091" +
   "\u000c\u0000\u0000\u0000\u0004\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c5\u0002\u0000\u0000\u00fb\u0002\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00d2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0028\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0065\u0076\u0074\u0041" +
   "\u0067\u0065\u006e\u0074\u0049\u006e\u0066\u006f" +
   "\u0054\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u00aa\u0000\u0000\u0000" +
   "\u0046\u004a\u002e\u0041\u0047\u0045\u004e\u0054" +
   "\u002e\u0025\u0073\u002e\u0045\u0056\u0054\u002e" +
   "\u0049\u004e\u0046\u004f\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_9892032ea4e69c6b =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u006b\u009c\u00e6\u00a4\u002e\u0003\u0092\u0098" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0003\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00fd\u0002\u0000\u0000\u0061\u0003\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u00af\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0053\u0074\u0061\u0072" +
   "\u0074\u0057\u006f\u0072\u006b\u0065\u0072\u0052" +
   "\u0065\u0071\u0075\u0065\u0073\u0074\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0045\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0040\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u004c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0049\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0044\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0060\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u005d\u0000\u0000\u0000\"\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0058\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0074\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0063\u006f\u006d\u006d\u0061\u006e\u0064\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0072\u0067\u0073\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0065\u006e\u0076\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000e\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_c5f4047bf39fa88d =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u008d\u00a8\u009f\u00f3\u007b\u0004\u00f4\u00c5" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u0003\u0000\u0000\u0095\u0003\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u0002\u0001\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0053\u0074\u0061\u0072" +
   "\u0074\u0057\u006f\u0072\u006b\u0065\u0072\u0052" +
   "\u0065\u0073\u0070\u006f\u006e\u0073\u0065\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0065\u0072\u0072\u006f\u0072\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_b15c44a86e45d3b0 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00b0\u00d3\u0045\u006e\u00a8\u0044\\\u00b1" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0097\u0003\u0000\u0000\u00b2\u0003\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00f2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0053\u0074\u006f\u0070" +
   "\u0057\u006f\u0072\u006b\u0065\u0072\u0052\u0065" +
   "\u0071\u0075\u0065\u0073\u0074\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" + "");
public static final org.capnproto.SegmentReader b_dea9ade321ec73b3 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00b3\u0073\u00ec\u0021\u00e3\u00ad\u00a9\u00de" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b4\u0003\u0000\u0000\u00e5\u0003\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0053\u0074\u006f\u0070" +
   "\u0057\u006f\u0072\u006b\u0065\u0072\u0052\u0065" +
   "\u0073\u0070\u006f\u006e\u0073\u0065\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0032\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0065\u0072\u0072\u006f\u0072\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a62a70011c9fd5df =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00df\u00d5\u009f\u001c\u0001\u0070\u002a\u00a6" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e7\u0003\u0000\u0000\u001a\u0004\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00fa\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0055\u0070\u0064\u0061" +
   "\u0074\u0065\u0057\u006f\u0072\u006b\u0065\u0072" +
   "\u0053\u0074\u0061\u0074\u0075\u0073\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0073\u0074\u0061\u0074\u0075\u0073\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0005\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a76a3a9604a9e962 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0062\u00e9\u00a9\u0004\u0096\u003a\u006a\u00a7" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0004\u0000\u0000\u004b\u0004\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00f2\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0055\u0070\u0064\u0061" +
   "\u0074\u0065\u0057\u006f\u0072\u006b\u0065\u0072" +
   "\u0053\u0074\u0064\u0069\u006f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u002a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0008\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0014\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0064\u0061\u0074\u0061\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\r\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_a073b10fb899cbb0 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00b0\u00cb\u0099\u00b8\u000f\u00b1\u0073\u00a0" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0004\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u004d\u0004\u0000\u0000\u00c1\u0004\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00ea\u0000\u0000\u0000" +
   "\u0021\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u00e7\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u0055\u0070\u0064\u0061" +
   "\u0074\u0065\u0043\u006c\u0069\u0065\u006e\u0074" +
   "\u0049\u006e\u0066\u006f\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0010\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0060\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u006c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0069\u0000\u0000\u0000\u004a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0068\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0074\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u0000\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0071\u0000\u0000\u0000\u003a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006c\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0078\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u0000\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0070\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u007c\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0075\u0073\u0065\u0072\u006e\u0061\u006d\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0068\u006f\u0073\u0074\u006e\u0061\u006d\u0065" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0079\u0073\u0074\u0065\u006d\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0064\u0064\u0072\u0065\u0073\u0073\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u000c\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
public static final org.capnproto.SegmentReader b_d270ea7f372f79cd =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u00cd\u0079\u002f\u0037\u007f\u00ea\u0070\u00d2" +
   "\u000c\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0070\u008b\u00aa\u0036\u005d\u00aa\u00cc\u00dc" +
   "\u0001\u0000\u0007\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c3\u0004\u0000\u0000\u004f\u0006\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u001d\u0000\u0000\u0000\u0007\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u003f\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u004d\u0065\u0073\u0073" +
   "\u0061\u0067\u0065\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u0004\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0011\u00aa\u0057\u0019\u00a2\u002f\u0065\u00b4" +
   "\r\u0000\u0000\u0000\u0042\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0000" + "");
public static final org.capnproto.SegmentReader b_b4652fa21957aa11 =
   org.capnproto.GeneratedClassSupport.decodeRawBytes(
   "\u0000\u0000\u0000\u0000\u0006\u0000\u0006\u0000" +
   "\u0011\u00aa\u0057\u0019\u00a2\u002f\u0065\u00b4" +
   "\u0014\u0000\u0000\u0000\u0001\u0000\u0001\u0000" +
   "\u00cd\u0079\u002f\u0037\u007f\u00ea\u0070\u00d2" +
   "\u0001\u0000\u0007\u0000\u0001\u0000\u0007\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0015\u0000\u0000\u0000\u00e2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0019\u0000\u0000\u0000\u008f\u0001\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0061\u0067\u0065\u006e\u0074\u002e\u0063\u0061" +
   "\u0070\u006e\u0070\u003a\u004d\u0065\u0073\u0073" +
   "\u0061\u0067\u0065\u002e\u0063\u006f\u006e\u0074" +
   "\u0065\u006e\u0074\u0000\u0000\u0000\u0000\u0000" +
   "\u001c\u0000\u0000\u0000\u0003\u0000\u0004\u0000" +
   "\u0000\u0000\u00ff\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b5\u0000\u0000\u0000\u009a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b8\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00c4\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0001\u0000\u00fe\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0001\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c1\u0000\u0000\u0000\u00a2\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00c4\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00d0\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0002\u0000\u00fd\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0002\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00cd\u0000\u0000\u0000\u0092\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00d0\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00dc\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0003\u0000\u00fc\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0003\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00d9\u0000\u0000\u0000\u009a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00dc\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00e8\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0004\u0000\u00fb\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0004\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e5\u0000\u0000\u0000\u009a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00e8\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u00f4\u0000\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0005\u0000\u00fa\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0005\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f1\u0000\u0000\u0000\u0092\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00f4\u0000\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u0000\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0006\u0000\u00f9\u00ff\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0001\u0000\u0006\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00fd\u0000\u0000\u0000\u008a\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0001\u0000\u0000\u0003\u0000\u0001\u0000" +
   "\u000c\u0001\u0000\u0000\u0002\u0000\u0001\u0000" +
   "\u0073\u0074\u0061\u0072\u0074\u0057\u006f\u0072" +
   "\u006b\u0065\u0072\u0052\u0065\u0071\u0075\u0065" +
   "\u0073\u0074\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u006b\u009c\u00e6\u00a4\u002e\u0003\u0092\u0098" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0074\u0061\u0072\u0074\u0057\u006f\u0072" +
   "\u006b\u0065\u0072\u0052\u0065\u0073\u0070\u006f" +
   "\u006e\u0073\u0065\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u008d\u00a8\u009f\u00f3\u007b\u0004\u00f4\u00c5" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0074\u006f\u0070\u0057\u006f\u0072\u006b" +
   "\u0065\u0072\u0052\u0065\u0071\u0075\u0065\u0073" +
   "\u0074\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b0\u00d3\u0045\u006e\u00a8\u0044\\\u00b1" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0073\u0074\u006f\u0070\u0057\u006f\u0072\u006b" +
   "\u0065\u0072\u0052\u0065\u0073\u0070\u006f\u006e" +
   "\u0073\u0065\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b3\u0073\u00ec\u0021\u00e3\u00ad\u00a9\u00de" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u0070\u0064\u0061\u0074\u0065\u0057\u006f" +
   "\u0072\u006b\u0065\u0072\u0053\u0074\u0061\u0074" +
   "\u0075\u0073\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00df\u00d5\u009f\u001c\u0001\u0070\u002a\u00a6" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u0070\u0064\u0061\u0074\u0065\u0057\u006f" +
   "\u0072\u006b\u0065\u0072\u0053\u0074\u0064\u0069" +
   "\u006f\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0062\u00e9\u00a9\u0004\u0096\u003a\u006a\u00a7" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0075\u0070\u0064\u0061\u0074\u0065\u0043\u006c" +
   "\u0069\u0065\u006e\u0074\u0049\u006e\u0066\u006f" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u00b0\u00cb\u0099\u00b8\u000f\u00b1\u0073\u00a0" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" +
   "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000" + "");
}
}

