// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: gateway.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1002000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(e877d4d779915127);
CAPNP_DECLARE_SCHEMA(810386dac7b63aa0);
CAPNP_DECLARE_SCHEMA(9d537ec7d57e7b00);
CAPNP_DECLARE_SCHEMA(d7869072df1ea7a4);
CAPNP_DECLARE_SCHEMA(bd43af87875aa50f);
CAPNP_DECLARE_SCHEMA(dfa13ac00d6999df);
CAPNP_DECLARE_SCHEMA(8358411f7810f89d);
CAPNP_DECLARE_SCHEMA(d87ca8be1392abb0);
CAPNP_DECLARE_SCHEMA(94fd232aa8c03fe3);
CAPNP_DECLARE_SCHEMA(a5ef8e64ccf7b7f9);
CAPNP_DECLARE_SCHEMA(992afdc987d01804);
CAPNP_DECLARE_SCHEMA(f1d70533ecfbb5d6);
CAPNP_DECLARE_SCHEMA(ac586d10965c3f94);

}  // namespace schemas
}  // namespace capnp


extern const ::capnp::_::ConstText<35> CMD_REGISTER_T;
extern const ::capnp::_::ConstText<37> CMD_UNREGISTER_T;
extern const ::capnp::_::ConstText<35> EVT_REGISTER_T;
extern const ::capnp::_::ConstText<37> EVT_UNREGISTER_T;
struct Property {
  Property() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(bd43af87875aa50f, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct RegisterAgentRequest {
  RegisterAgentRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dfa13ac00d6999df, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct RegisterAgentResponse {
  RegisterAgentResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8358411f7810f89d, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UnregisterAgentRequest {
  UnregisterAgentRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d87ca8be1392abb0, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct UnregisterAgentResponse {
  UnregisterAgentResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(94fd232aa8c03fe3, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Error {
  Error() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a5ef8e64ccf7b7f9, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Message {
  Message() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Content;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(992afdc987d01804, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Message::Content {
  Content() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    REGISTER_AGENT_REQUEST,
    REGISTER_AGENT_RESPONSE,
    UNREGISTER_AGENT_REQUEST,
    UNREGISTER_AGENT_RESPONSE,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f1d70533ecfbb5d6, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Envelope {
  Envelope() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(ac586d10965c3f94, 0, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Property::Reader {
public:
  typedef Property Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasKey() const;
  inline  ::capnp::Text::Reader getKey() const;

  inline bool hasValue() const;
  inline  ::capnp::Text::Reader getValue() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Property::Builder {
public:
  typedef Property Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasKey();
  inline  ::capnp::Text::Builder getKey();
  inline void setKey( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initKey(unsigned int size);
  inline void adoptKey(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownKey();

  inline bool hasValue();
  inline  ::capnp::Text::Builder getValue();
  inline void setValue( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initValue(unsigned int size);
  inline void adoptValue(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownValue();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Property::Pipeline {
public:
  typedef Property Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RegisterAgentRequest::Reader {
public:
  typedef RegisterAgentRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasProperties() const;
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader getProperties() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RegisterAgentRequest::Builder {
public:
  typedef RegisterAgentRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasProperties();
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder getProperties();
  inline void setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder initProperties(unsigned int size);
  inline void adoptProperties(::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> disownProperties();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RegisterAgentRequest::Pipeline {
public:
  typedef RegisterAgentRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class RegisterAgentResponse::Reader {
public:
  typedef RegisterAgentResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasProperties() const;
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader getProperties() const;

  inline bool hasError() const;
  inline  ::Error::Reader getError() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RegisterAgentResponse::Builder {
public:
  typedef RegisterAgentResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasProperties();
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder getProperties();
  inline void setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder initProperties(unsigned int size);
  inline void adoptProperties(::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> disownProperties();

  inline bool hasError();
  inline  ::Error::Builder getError();
  inline void setError( ::Error::Reader value);
  inline  ::Error::Builder initError();
  inline void adoptError(::capnp::Orphan< ::Error>&& value);
  inline ::capnp::Orphan< ::Error> disownError();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RegisterAgentResponse::Pipeline {
public:
  typedef RegisterAgentResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Error::Pipeline getError();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UnregisterAgentRequest::Reader {
public:
  typedef UnregisterAgentRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasProperties() const;
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader getProperties() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UnregisterAgentRequest::Builder {
public:
  typedef UnregisterAgentRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasProperties();
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder getProperties();
  inline void setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder initProperties(unsigned int size);
  inline void adoptProperties(::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> disownProperties();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UnregisterAgentRequest::Pipeline {
public:
  typedef UnregisterAgentRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class UnregisterAgentResponse::Reader {
public:
  typedef UnregisterAgentResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasProperties() const;
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader getProperties() const;

  inline bool hasError() const;
  inline  ::Error::Reader getError() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class UnregisterAgentResponse::Builder {
public:
  typedef UnregisterAgentResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasProperties();
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder getProperties();
  inline void setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value);
  inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder initProperties(unsigned int size);
  inline void adoptProperties(::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> disownProperties();

  inline bool hasError();
  inline  ::Error::Builder getError();
  inline void setError( ::Error::Reader value);
  inline  ::Error::Builder initError();
  inline void adoptError(::capnp::Orphan< ::Error>&& value);
  inline ::capnp::Orphan< ::Error> disownError();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class UnregisterAgentResponse::Pipeline {
public:
  typedef UnregisterAgentResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Error::Pipeline getError();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Error::Reader {
public:
  typedef Error Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::int32_t getCode() const;

  inline bool hasMessage() const;
  inline  ::capnp::Text::Reader getMessage() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Error::Builder {
public:
  typedef Error Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::int32_t getCode();
  inline void setCode( ::int32_t value);

  inline bool hasMessage();
  inline  ::capnp::Text::Builder getMessage();
  inline void setMessage( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initMessage(unsigned int size);
  inline void adoptMessage(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownMessage();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Error::Pipeline {
public:
  typedef Error Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Message::Reader {
public:
  typedef Message Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename Content::Reader getContent() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Message::Builder {
public:
  typedef Message Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename Content::Builder getContent();
  inline typename Content::Builder initContent();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Message::Pipeline {
public:
  typedef Message Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename Content::Pipeline getContent();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Message::Content::Reader {
public:
  typedef Content Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isRegisterAgentRequest() const;
  inline bool hasRegisterAgentRequest() const;
  inline  ::RegisterAgentRequest::Reader getRegisterAgentRequest() const;

  inline bool isRegisterAgentResponse() const;
  inline bool hasRegisterAgentResponse() const;
  inline  ::RegisterAgentResponse::Reader getRegisterAgentResponse() const;

  inline bool isUnregisterAgentRequest() const;
  inline bool hasUnregisterAgentRequest() const;
  inline  ::UnregisterAgentRequest::Reader getUnregisterAgentRequest() const;

  inline bool isUnregisterAgentResponse() const;
  inline bool hasUnregisterAgentResponse() const;
  inline  ::UnregisterAgentResponse::Reader getUnregisterAgentResponse() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Message::Content::Builder {
public:
  typedef Content Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isRegisterAgentRequest();
  inline bool hasRegisterAgentRequest();
  inline  ::RegisterAgentRequest::Builder getRegisterAgentRequest();
  inline void setRegisterAgentRequest( ::RegisterAgentRequest::Reader value);
  inline  ::RegisterAgentRequest::Builder initRegisterAgentRequest();
  inline void adoptRegisterAgentRequest(::capnp::Orphan< ::RegisterAgentRequest>&& value);
  inline ::capnp::Orphan< ::RegisterAgentRequest> disownRegisterAgentRequest();

  inline bool isRegisterAgentResponse();
  inline bool hasRegisterAgentResponse();
  inline  ::RegisterAgentResponse::Builder getRegisterAgentResponse();
  inline void setRegisterAgentResponse( ::RegisterAgentResponse::Reader value);
  inline  ::RegisterAgentResponse::Builder initRegisterAgentResponse();
  inline void adoptRegisterAgentResponse(::capnp::Orphan< ::RegisterAgentResponse>&& value);
  inline ::capnp::Orphan< ::RegisterAgentResponse> disownRegisterAgentResponse();

  inline bool isUnregisterAgentRequest();
  inline bool hasUnregisterAgentRequest();
  inline  ::UnregisterAgentRequest::Builder getUnregisterAgentRequest();
  inline void setUnregisterAgentRequest( ::UnregisterAgentRequest::Reader value);
  inline  ::UnregisterAgentRequest::Builder initUnregisterAgentRequest();
  inline void adoptUnregisterAgentRequest(::capnp::Orphan< ::UnregisterAgentRequest>&& value);
  inline ::capnp::Orphan< ::UnregisterAgentRequest> disownUnregisterAgentRequest();

  inline bool isUnregisterAgentResponse();
  inline bool hasUnregisterAgentResponse();
  inline  ::UnregisterAgentResponse::Builder getUnregisterAgentResponse();
  inline void setUnregisterAgentResponse( ::UnregisterAgentResponse::Reader value);
  inline  ::UnregisterAgentResponse::Builder initUnregisterAgentResponse();
  inline void adoptUnregisterAgentResponse(::capnp::Orphan< ::UnregisterAgentResponse>&& value);
  inline ::capnp::Orphan< ::UnregisterAgentResponse> disownUnregisterAgentResponse();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Message::Content::Pipeline {
public:
  typedef Content Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Envelope::Reader {
public:
  typedef Envelope Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasSubject() const;
  inline  ::capnp::Text::Reader getSubject() const;

  inline bool hasPayload() const;
  inline  ::Message::Reader getPayload() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Envelope::Builder {
public:
  typedef Envelope Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasSubject();
  inline  ::capnp::Text::Builder getSubject();
  inline void setSubject( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initSubject(unsigned int size);
  inline void adoptSubject(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownSubject();

  inline bool hasPayload();
  inline  ::Message::Builder getPayload();
  inline void setPayload( ::Message::Reader value);
  inline  ::Message::Builder initPayload();
  inline void adoptPayload(::capnp::Orphan< ::Message>&& value);
  inline ::capnp::Orphan< ::Message> disownPayload();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Envelope::Pipeline {
public:
  typedef Envelope Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::Message::Pipeline getPayload();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool Property::Reader::hasKey() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Property::Builder::hasKey() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Property::Reader::getKey() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Property::Builder::getKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Property::Builder::setKey( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Property::Builder::initKey(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Property::Builder::adoptKey(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Property::Builder::disownKey() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Property::Reader::hasValue() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Property::Builder::hasValue() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Property::Reader::getValue() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Property::Builder::getValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Property::Builder::setValue( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Property::Builder::initValue(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Property::Builder::adoptValue(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Property::Builder::disownValue() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool RegisterAgentRequest::Reader::hasProperties() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool RegisterAgentRequest::Builder::hasProperties() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader RegisterAgentRequest::Reader::getProperties() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder RegisterAgentRequest::Builder::getProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void RegisterAgentRequest::Builder::setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder RegisterAgentRequest::Builder::initProperties(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void RegisterAgentRequest::Builder::adoptProperties(
    ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> RegisterAgentRequest::Builder::disownProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool RegisterAgentResponse::Reader::hasProperties() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool RegisterAgentResponse::Builder::hasProperties() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader RegisterAgentResponse::Reader::getProperties() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder RegisterAgentResponse::Builder::getProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void RegisterAgentResponse::Builder::setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder RegisterAgentResponse::Builder::initProperties(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void RegisterAgentResponse::Builder::adoptProperties(
    ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> RegisterAgentResponse::Builder::disownProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool RegisterAgentResponse::Reader::hasError() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool RegisterAgentResponse::Builder::hasError() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::Error::Reader RegisterAgentResponse::Reader::getError() const {
  return ::capnp::_::PointerHelpers< ::Error>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::Error::Builder RegisterAgentResponse::Builder::getError() {
  return ::capnp::_::PointerHelpers< ::Error>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Error::Pipeline RegisterAgentResponse::Pipeline::getError() {
  return  ::Error::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void RegisterAgentResponse::Builder::setError( ::Error::Reader value) {
  ::capnp::_::PointerHelpers< ::Error>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::Error::Builder RegisterAgentResponse::Builder::initError() {
  return ::capnp::_::PointerHelpers< ::Error>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void RegisterAgentResponse::Builder::adoptError(
    ::capnp::Orphan< ::Error>&& value) {
  ::capnp::_::PointerHelpers< ::Error>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Error> RegisterAgentResponse::Builder::disownError() {
  return ::capnp::_::PointerHelpers< ::Error>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool UnregisterAgentRequest::Reader::hasProperties() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UnregisterAgentRequest::Builder::hasProperties() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader UnregisterAgentRequest::Reader::getProperties() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder UnregisterAgentRequest::Builder::getProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UnregisterAgentRequest::Builder::setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder UnregisterAgentRequest::Builder::initProperties(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UnregisterAgentRequest::Builder::adoptProperties(
    ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> UnregisterAgentRequest::Builder::disownProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UnregisterAgentResponse::Reader::hasProperties() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool UnregisterAgentResponse::Builder::hasProperties() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader UnregisterAgentResponse::Reader::getProperties() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder UnregisterAgentResponse::Builder::getProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void UnregisterAgentResponse::Builder::setProperties( ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>::Builder UnregisterAgentResponse::Builder::initProperties(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void UnregisterAgentResponse::Builder::adoptProperties(
    ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>> UnregisterAgentResponse::Builder::disownProperties() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::Property,  ::capnp::Kind::STRUCT>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool UnregisterAgentResponse::Reader::hasError() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool UnregisterAgentResponse::Builder::hasError() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::Error::Reader UnregisterAgentResponse::Reader::getError() const {
  return ::capnp::_::PointerHelpers< ::Error>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::Error::Builder UnregisterAgentResponse::Builder::getError() {
  return ::capnp::_::PointerHelpers< ::Error>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Error::Pipeline UnregisterAgentResponse::Pipeline::getError() {
  return  ::Error::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void UnregisterAgentResponse::Builder::setError( ::Error::Reader value) {
  ::capnp::_::PointerHelpers< ::Error>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::Error::Builder UnregisterAgentResponse::Builder::initError() {
  return ::capnp::_::PointerHelpers< ::Error>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void UnregisterAgentResponse::Builder::adoptError(
    ::capnp::Orphan< ::Error>&& value) {
  ::capnp::_::PointerHelpers< ::Error>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Error> UnregisterAgentResponse::Builder::disownError() {
  return ::capnp::_::PointerHelpers< ::Error>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline  ::int32_t Error::Reader::getCode() const {
  return _reader.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::int32_t Error::Builder::getCode() {
  return _builder.getDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Error::Builder::setCode( ::int32_t value) {
  _builder.setDataField< ::int32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Error::Reader::hasMessage() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Error::Builder::hasMessage() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Error::Reader::getMessage() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Error::Builder::getMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Error::Builder::setMessage( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Error::Builder::initMessage(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Error::Builder::adoptMessage(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Error::Builder::disownMessage() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline typename Message::Content::Reader Message::Reader::getContent() const {
  return typename Message::Content::Reader(_reader);
}
inline typename Message::Content::Builder Message::Builder::getContent() {
  return typename Message::Content::Builder(_builder);
}
#if !CAPNP_LITE
inline typename Message::Content::Pipeline Message::Pipeline::getContent() {
  return typename Message::Content::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename Message::Content::Builder Message::Builder::initContent() {
  _builder.setDataField< ::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  return typename Message::Content::Builder(_builder);
}
inline  ::Message::Content::Which Message::Content::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::Message::Content::Which Message::Content::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Message::Content::Reader::isRegisterAgentRequest() const {
  return which() == Message::Content::REGISTER_AGENT_REQUEST;
}
inline bool Message::Content::Builder::isRegisterAgentRequest() {
  return which() == Message::Content::REGISTER_AGENT_REQUEST;
}
inline bool Message::Content::Reader::hasRegisterAgentRequest() const {
  if (which() != Message::Content::REGISTER_AGENT_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Content::Builder::hasRegisterAgentRequest() {
  if (which() != Message::Content::REGISTER_AGENT_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::RegisterAgentRequest::Reader Message::Content::Reader::getRegisterAgentRequest() const {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::RegisterAgentRequest::Builder Message::Content::Builder::getRegisterAgentRequest() {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::setRegisterAgentRequest( ::RegisterAgentRequest::Reader value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_REQUEST);
  ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::RegisterAgentRequest::Builder Message::Content::Builder::initRegisterAgentRequest() {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_REQUEST);
  return ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::adoptRegisterAgentRequest(
    ::capnp::Orphan< ::RegisterAgentRequest>&& value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_REQUEST);
  ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::RegisterAgentRequest> Message::Content::Builder::disownRegisterAgentRequest() {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Content::Reader::isRegisterAgentResponse() const {
  return which() == Message::Content::REGISTER_AGENT_RESPONSE;
}
inline bool Message::Content::Builder::isRegisterAgentResponse() {
  return which() == Message::Content::REGISTER_AGENT_RESPONSE;
}
inline bool Message::Content::Reader::hasRegisterAgentResponse() const {
  if (which() != Message::Content::REGISTER_AGENT_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Content::Builder::hasRegisterAgentResponse() {
  if (which() != Message::Content::REGISTER_AGENT_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::RegisterAgentResponse::Reader Message::Content::Reader::getRegisterAgentResponse() const {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::RegisterAgentResponse::Builder Message::Content::Builder::getRegisterAgentResponse() {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::setRegisterAgentResponse( ::RegisterAgentResponse::Reader value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_RESPONSE);
  ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::RegisterAgentResponse::Builder Message::Content::Builder::initRegisterAgentResponse() {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_RESPONSE);
  return ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::adoptRegisterAgentResponse(
    ::capnp::Orphan< ::RegisterAgentResponse>&& value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::REGISTER_AGENT_RESPONSE);
  ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::RegisterAgentResponse> Message::Content::Builder::disownRegisterAgentResponse() {
  KJ_IREQUIRE((which() == Message::Content::REGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::RegisterAgentResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Content::Reader::isUnregisterAgentRequest() const {
  return which() == Message::Content::UNREGISTER_AGENT_REQUEST;
}
inline bool Message::Content::Builder::isUnregisterAgentRequest() {
  return which() == Message::Content::UNREGISTER_AGENT_REQUEST;
}
inline bool Message::Content::Reader::hasUnregisterAgentRequest() const {
  if (which() != Message::Content::UNREGISTER_AGENT_REQUEST) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Content::Builder::hasUnregisterAgentRequest() {
  if (which() != Message::Content::UNREGISTER_AGENT_REQUEST) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::UnregisterAgentRequest::Reader Message::Content::Reader::getUnregisterAgentRequest() const {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UnregisterAgentRequest::Builder Message::Content::Builder::getUnregisterAgentRequest() {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::setUnregisterAgentRequest( ::UnregisterAgentRequest::Reader value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_REQUEST);
  ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::UnregisterAgentRequest::Builder Message::Content::Builder::initUnregisterAgentRequest() {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_REQUEST);
  return ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::adoptUnregisterAgentRequest(
    ::capnp::Orphan< ::UnregisterAgentRequest>&& value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_REQUEST);
  ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UnregisterAgentRequest> Message::Content::Builder::disownUnregisterAgentRequest() {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_REQUEST),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentRequest>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Message::Content::Reader::isUnregisterAgentResponse() const {
  return which() == Message::Content::UNREGISTER_AGENT_RESPONSE;
}
inline bool Message::Content::Builder::isUnregisterAgentResponse() {
  return which() == Message::Content::UNREGISTER_AGENT_RESPONSE;
}
inline bool Message::Content::Reader::hasUnregisterAgentResponse() const {
  if (which() != Message::Content::UNREGISTER_AGENT_RESPONSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Message::Content::Builder::hasUnregisterAgentResponse() {
  if (which() != Message::Content::UNREGISTER_AGENT_RESPONSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::UnregisterAgentResponse::Reader Message::Content::Reader::getUnregisterAgentResponse() const {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::UnregisterAgentResponse::Builder Message::Content::Builder::getUnregisterAgentResponse() {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::setUnregisterAgentResponse( ::UnregisterAgentResponse::Reader value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_RESPONSE);
  ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::UnregisterAgentResponse::Builder Message::Content::Builder::initUnregisterAgentResponse() {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_RESPONSE);
  return ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Message::Content::Builder::adoptUnregisterAgentResponse(
    ::capnp::Orphan< ::UnregisterAgentResponse>&& value) {
  _builder.setDataField<Message::Content::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Message::Content::UNREGISTER_AGENT_RESPONSE);
  ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::UnregisterAgentResponse> Message::Content::Builder::disownUnregisterAgentResponse() {
  KJ_IREQUIRE((which() == Message::Content::UNREGISTER_AGENT_RESPONSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::UnregisterAgentResponse>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Envelope::Reader::hasSubject() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Envelope::Builder::hasSubject() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Envelope::Reader::getSubject() const {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Envelope::Builder::getSubject() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Envelope::Builder::setSubject( ::capnp::Text::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Envelope::Builder::initSubject(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Envelope::Builder::adoptSubject(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Envelope::Builder::disownSubject() {
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Envelope::Reader::hasPayload() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Envelope::Builder::hasPayload() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::Message::Reader Envelope::Reader::getPayload() const {
  return ::capnp::_::PointerHelpers< ::Message>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::Message::Builder Envelope::Builder::getPayload() {
  return ::capnp::_::PointerHelpers< ::Message>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::Message::Pipeline Envelope::Pipeline::getPayload() {
  return  ::Message::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void Envelope::Builder::setPayload( ::Message::Reader value) {
  ::capnp::_::PointerHelpers< ::Message>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::Message::Builder Envelope::Builder::initPayload() {
  return ::capnp::_::PointerHelpers< ::Message>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Envelope::Builder::adoptPayload(
    ::capnp::Orphan< ::Message>&& value) {
  ::capnp::_::PointerHelpers< ::Message>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::Message> Envelope::Builder::disownPayload() {
  return ::capnp::_::PointerHelpers< ::Message>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

