// Code generated by capnpc-go. DO NOT EDIT.

package gateway

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Constants defined in gateway.capnp.
const (
	CmdRegisterT   = "FJ.GATEWAY.%s.CMD.AGENT.%s.REGISTER"
	CmdUnregisterT = "FJ.GATEWAY.%s.CMD.AGENT.%s.UNREGISTER"
	EvtRegisterT   = "FJ.GATEWAY.%s.EVT.AGENT.%s.REGISTER"
	EvtUnregisterT = "FJ.GATEWAY.%s.EVT.AGENT.%s.UNREGISTER"
)

type Property capnp.Struct

// Property_TypeID is the unique identifier for the type Property.
const Property_TypeID = 0xbd43af87875aa50f

func NewProperty(s *capnp.Segment) (Property, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Property(st), err
}

func NewRootProperty(s *capnp.Segment) (Property, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Property(st), err
}

func ReadRootProperty(msg *capnp.Message) (Property, error) {
	root, err := msg.Root()
	return Property(root.Struct()), err
}

func (s Property) String() string {
	str, _ := text.Marshal(0xbd43af87875aa50f, capnp.Struct(s))
	return str
}

func (s Property) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Property) DecodeFromPtr(p capnp.Ptr) Property {
	return Property(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Property) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Property) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Property) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Property) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Property) Key() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Property) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Property) KeyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Property) SetKey(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Property) Value() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Property) HasValue() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Property) ValueBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Property) SetValue(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Property_List is a list of Property.
type Property_List = capnp.StructList[Property]

// NewProperty creates a new list of Property.
func NewProperty_List(s *capnp.Segment, sz int32) (Property_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Property](l), err
}

// Property_Future is a wrapper for a Property promised by a client call.
type Property_Future struct{ *capnp.Future }

func (f Property_Future) Struct() (Property, error) {
	p, err := f.Future.Ptr()
	return Property(p.Struct()), err
}

type RegisterAgentRequest capnp.Struct

// RegisterAgentRequest_TypeID is the unique identifier for the type RegisterAgentRequest.
const RegisterAgentRequest_TypeID = 0xdfa13ac00d6999df

func NewRegisterAgentRequest(s *capnp.Segment) (RegisterAgentRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RegisterAgentRequest(st), err
}

func NewRootRegisterAgentRequest(s *capnp.Segment) (RegisterAgentRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return RegisterAgentRequest(st), err
}

func ReadRootRegisterAgentRequest(msg *capnp.Message) (RegisterAgentRequest, error) {
	root, err := msg.Root()
	return RegisterAgentRequest(root.Struct()), err
}

func (s RegisterAgentRequest) String() string {
	str, _ := text.Marshal(0xdfa13ac00d6999df, capnp.Struct(s))
	return str
}

func (s RegisterAgentRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RegisterAgentRequest) DecodeFromPtr(p capnp.Ptr) RegisterAgentRequest {
	return RegisterAgentRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RegisterAgentRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RegisterAgentRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RegisterAgentRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RegisterAgentRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RegisterAgentRequest) Properties() (Property_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Property_List(p.List()), err
}

func (s RegisterAgentRequest) HasProperties() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RegisterAgentRequest) SetProperties(v Property_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewProperties sets the properties field to a newly
// allocated Property_List, preferring placement in s's segment.
func (s RegisterAgentRequest) NewProperties(n int32) (Property_List, error) {
	l, err := NewProperty_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Property_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// RegisterAgentRequest_List is a list of RegisterAgentRequest.
type RegisterAgentRequest_List = capnp.StructList[RegisterAgentRequest]

// NewRegisterAgentRequest creates a new list of RegisterAgentRequest.
func NewRegisterAgentRequest_List(s *capnp.Segment, sz int32) (RegisterAgentRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[RegisterAgentRequest](l), err
}

// RegisterAgentRequest_Future is a wrapper for a RegisterAgentRequest promised by a client call.
type RegisterAgentRequest_Future struct{ *capnp.Future }

func (f RegisterAgentRequest_Future) Struct() (RegisterAgentRequest, error) {
	p, err := f.Future.Ptr()
	return RegisterAgentRequest(p.Struct()), err
}

type RegisterAgentResponse capnp.Struct

// RegisterAgentResponse_TypeID is the unique identifier for the type RegisterAgentResponse.
const RegisterAgentResponse_TypeID = 0x8358411f7810f89d

func NewRegisterAgentResponse(s *capnp.Segment) (RegisterAgentResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RegisterAgentResponse(st), err
}

func NewRootRegisterAgentResponse(s *capnp.Segment) (RegisterAgentResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return RegisterAgentResponse(st), err
}

func ReadRootRegisterAgentResponse(msg *capnp.Message) (RegisterAgentResponse, error) {
	root, err := msg.Root()
	return RegisterAgentResponse(root.Struct()), err
}

func (s RegisterAgentResponse) String() string {
	str, _ := text.Marshal(0x8358411f7810f89d, capnp.Struct(s))
	return str
}

func (s RegisterAgentResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RegisterAgentResponse) DecodeFromPtr(p capnp.Ptr) RegisterAgentResponse {
	return RegisterAgentResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RegisterAgentResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RegisterAgentResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RegisterAgentResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RegisterAgentResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RegisterAgentResponse) Properties() (Property_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Property_List(p.List()), err
}

func (s RegisterAgentResponse) HasProperties() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RegisterAgentResponse) SetProperties(v Property_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewProperties sets the properties field to a newly
// allocated Property_List, preferring placement in s's segment.
func (s RegisterAgentResponse) NewProperties(n int32) (Property_List, error) {
	l, err := NewProperty_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Property_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s RegisterAgentResponse) Error() (Error, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Error(p.Struct()), err
}

func (s RegisterAgentResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RegisterAgentResponse) SetError(v Error) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated Error struct, preferring placement in s's segment.
func (s RegisterAgentResponse) NewError() (Error, error) {
	ss, err := NewError(capnp.Struct(s).Segment())
	if err != nil {
		return Error{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// RegisterAgentResponse_List is a list of RegisterAgentResponse.
type RegisterAgentResponse_List = capnp.StructList[RegisterAgentResponse]

// NewRegisterAgentResponse creates a new list of RegisterAgentResponse.
func NewRegisterAgentResponse_List(s *capnp.Segment, sz int32) (RegisterAgentResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[RegisterAgentResponse](l), err
}

// RegisterAgentResponse_Future is a wrapper for a RegisterAgentResponse promised by a client call.
type RegisterAgentResponse_Future struct{ *capnp.Future }

func (f RegisterAgentResponse_Future) Struct() (RegisterAgentResponse, error) {
	p, err := f.Future.Ptr()
	return RegisterAgentResponse(p.Struct()), err
}
func (p RegisterAgentResponse_Future) Error() Error_Future {
	return Error_Future{Future: p.Future.Field(1, nil)}
}

type UnregisterAgentRequest capnp.Struct

// UnregisterAgentRequest_TypeID is the unique identifier for the type UnregisterAgentRequest.
const UnregisterAgentRequest_TypeID = 0xd87ca8be1392abb0

func NewUnregisterAgentRequest(s *capnp.Segment) (UnregisterAgentRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UnregisterAgentRequest(st), err
}

func NewRootUnregisterAgentRequest(s *capnp.Segment) (UnregisterAgentRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UnregisterAgentRequest(st), err
}

func ReadRootUnregisterAgentRequest(msg *capnp.Message) (UnregisterAgentRequest, error) {
	root, err := msg.Root()
	return UnregisterAgentRequest(root.Struct()), err
}

func (s UnregisterAgentRequest) String() string {
	str, _ := text.Marshal(0xd87ca8be1392abb0, capnp.Struct(s))
	return str
}

func (s UnregisterAgentRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UnregisterAgentRequest) DecodeFromPtr(p capnp.Ptr) UnregisterAgentRequest {
	return UnregisterAgentRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UnregisterAgentRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UnregisterAgentRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UnregisterAgentRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UnregisterAgentRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UnregisterAgentRequest) Properties() (Property_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Property_List(p.List()), err
}

func (s UnregisterAgentRequest) HasProperties() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UnregisterAgentRequest) SetProperties(v Property_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewProperties sets the properties field to a newly
// allocated Property_List, preferring placement in s's segment.
func (s UnregisterAgentRequest) NewProperties(n int32) (Property_List, error) {
	l, err := NewProperty_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Property_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// UnregisterAgentRequest_List is a list of UnregisterAgentRequest.
type UnregisterAgentRequest_List = capnp.StructList[UnregisterAgentRequest]

// NewUnregisterAgentRequest creates a new list of UnregisterAgentRequest.
func NewUnregisterAgentRequest_List(s *capnp.Segment, sz int32) (UnregisterAgentRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[UnregisterAgentRequest](l), err
}

// UnregisterAgentRequest_Future is a wrapper for a UnregisterAgentRequest promised by a client call.
type UnregisterAgentRequest_Future struct{ *capnp.Future }

func (f UnregisterAgentRequest_Future) Struct() (UnregisterAgentRequest, error) {
	p, err := f.Future.Ptr()
	return UnregisterAgentRequest(p.Struct()), err
}

type UnregisterAgentResponse capnp.Struct

// UnregisterAgentResponse_TypeID is the unique identifier for the type UnregisterAgentResponse.
const UnregisterAgentResponse_TypeID = 0x94fd232aa8c03fe3

func NewUnregisterAgentResponse(s *capnp.Segment) (UnregisterAgentResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return UnregisterAgentResponse(st), err
}

func NewRootUnregisterAgentResponse(s *capnp.Segment) (UnregisterAgentResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return UnregisterAgentResponse(st), err
}

func ReadRootUnregisterAgentResponse(msg *capnp.Message) (UnregisterAgentResponse, error) {
	root, err := msg.Root()
	return UnregisterAgentResponse(root.Struct()), err
}

func (s UnregisterAgentResponse) String() string {
	str, _ := text.Marshal(0x94fd232aa8c03fe3, capnp.Struct(s))
	return str
}

func (s UnregisterAgentResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UnregisterAgentResponse) DecodeFromPtr(p capnp.Ptr) UnregisterAgentResponse {
	return UnregisterAgentResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UnregisterAgentResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UnregisterAgentResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UnregisterAgentResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UnregisterAgentResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UnregisterAgentResponse) Properties() (Property_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Property_List(p.List()), err
}

func (s UnregisterAgentResponse) HasProperties() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UnregisterAgentResponse) SetProperties(v Property_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewProperties sets the properties field to a newly
// allocated Property_List, preferring placement in s's segment.
func (s UnregisterAgentResponse) NewProperties(n int32) (Property_List, error) {
	l, err := NewProperty_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Property_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s UnregisterAgentResponse) Error() (Error, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Error(p.Struct()), err
}

func (s UnregisterAgentResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UnregisterAgentResponse) SetError(v Error) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewError sets the error field to a newly
// allocated Error struct, preferring placement in s's segment.
func (s UnregisterAgentResponse) NewError() (Error, error) {
	ss, err := NewError(capnp.Struct(s).Segment())
	if err != nil {
		return Error{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// UnregisterAgentResponse_List is a list of UnregisterAgentResponse.
type UnregisterAgentResponse_List = capnp.StructList[UnregisterAgentResponse]

// NewUnregisterAgentResponse creates a new list of UnregisterAgentResponse.
func NewUnregisterAgentResponse_List(s *capnp.Segment, sz int32) (UnregisterAgentResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[UnregisterAgentResponse](l), err
}

// UnregisterAgentResponse_Future is a wrapper for a UnregisterAgentResponse promised by a client call.
type UnregisterAgentResponse_Future struct{ *capnp.Future }

func (f UnregisterAgentResponse_Future) Struct() (UnregisterAgentResponse, error) {
	p, err := f.Future.Ptr()
	return UnregisterAgentResponse(p.Struct()), err
}
func (p UnregisterAgentResponse_Future) Error() Error_Future {
	return Error_Future{Future: p.Future.Field(1, nil)}
}

type Error capnp.Struct

// Error_TypeID is the unique identifier for the type Error.
const Error_TypeID = 0xa5ef8e64ccf7b7f9

func NewError(s *capnp.Segment) (Error, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Error(st), err
}

func NewRootError(s *capnp.Segment) (Error, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Error(st), err
}

func ReadRootError(msg *capnp.Message) (Error, error) {
	root, err := msg.Root()
	return Error(root.Struct()), err
}

func (s Error) String() string {
	str, _ := text.Marshal(0xa5ef8e64ccf7b7f9, capnp.Struct(s))
	return str
}

func (s Error) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Error) DecodeFromPtr(p capnp.Ptr) Error {
	return Error(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Error) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Error) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Error) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Error) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Error) Code() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Error) SetCode(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s Error) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Error) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Error) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Error) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Error_List is a list of Error.
type Error_List = capnp.StructList[Error]

// NewError creates a new list of Error.
func NewError_List(s *capnp.Segment, sz int32) (Error_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Error](l), err
}

// Error_Future is a wrapper for a Error promised by a client call.
type Error_Future struct{ *capnp.Future }

func (f Error_Future) Struct() (Error, error) {
	p, err := f.Future.Ptr()
	return Error(p.Struct()), err
}

type Message capnp.Struct
type Message_content Message
type Message_content_Which uint16

const (
	Message_content_Which_registerAgentRequest    Message_content_Which = 0
	Message_content_Which_registerAgentResponse   Message_content_Which = 1
	Message_content_Which_unregisterAgentRequest  Message_content_Which = 2
	Message_content_Which_unregisterAgentResponse Message_content_Which = 3
)

func (w Message_content_Which) String() string {
	const s = "registerAgentRequestregisterAgentResponseunregisterAgentRequestunregisterAgentResponse"
	switch w {
	case Message_content_Which_registerAgentRequest:
		return s[0:20]
	case Message_content_Which_registerAgentResponse:
		return s[20:41]
	case Message_content_Which_unregisterAgentRequest:
		return s[41:63]
	case Message_content_Which_unregisterAgentResponse:
		return s[63:86]

	}
	return "Message_content_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0x992afdc987d01804

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0x992afdc987d01804, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Content() Message_content { return Message_content(s) }

func (s Message_content) Which() Message_content_Which {
	return Message_content_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_content) RegisterAgentRequest() (RegisterAgentRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != registerAgentRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return RegisterAgentRequest(p.Struct()), err
}

func (s Message_content) HasRegisterAgentRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetRegisterAgentRequest(v RegisterAgentRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRegisterAgentRequest sets the registerAgentRequest field to a newly
// allocated RegisterAgentRequest struct, preferring placement in s's segment.
func (s Message_content) NewRegisterAgentRequest() (RegisterAgentRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewRegisterAgentRequest(capnp.Struct(s).Segment())
	if err != nil {
		return RegisterAgentRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) RegisterAgentResponse() (RegisterAgentResponse, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != registerAgentResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return RegisterAgentResponse(p.Struct()), err
}

func (s Message_content) HasRegisterAgentResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetRegisterAgentResponse(v RegisterAgentResponse) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewRegisterAgentResponse sets the registerAgentResponse field to a newly
// allocated RegisterAgentResponse struct, preferring placement in s's segment.
func (s Message_content) NewRegisterAgentResponse() (RegisterAgentResponse, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewRegisterAgentResponse(capnp.Struct(s).Segment())
	if err != nil {
		return RegisterAgentResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UnregisterAgentRequest() (UnregisterAgentRequest, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != unregisterAgentRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UnregisterAgentRequest(p.Struct()), err
}

func (s Message_content) HasUnregisterAgentRequest() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUnregisterAgentRequest(v UnregisterAgentRequest) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUnregisterAgentRequest sets the unregisterAgentRequest field to a newly
// allocated UnregisterAgentRequest struct, preferring placement in s's segment.
func (s Message_content) NewUnregisterAgentRequest() (UnregisterAgentRequest, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewUnregisterAgentRequest(capnp.Struct(s).Segment())
	if err != nil {
		return UnregisterAgentRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UnregisterAgentResponse() (UnregisterAgentResponse, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != unregisterAgentResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UnregisterAgentResponse(p.Struct()), err
}

func (s Message_content) HasUnregisterAgentResponse() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUnregisterAgentResponse(v UnregisterAgentResponse) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUnregisterAgentResponse sets the unregisterAgentResponse field to a newly
// allocated UnregisterAgentResponse struct, preferring placement in s's segment.
func (s Message_content) NewUnregisterAgentResponse() (UnregisterAgentResponse, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewUnregisterAgentResponse(capnp.Struct(s).Segment())
	if err != nil {
		return UnregisterAgentResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Content() Message_content_Future { return Message_content_Future{p.Future} }

// Message_content_Future is a wrapper for a Message_content promised by a client call.
type Message_content_Future struct{ *capnp.Future }

func (f Message_content_Future) Struct() (Message_content, error) {
	p, err := f.Future.Ptr()
	return Message_content(p.Struct()), err
}
func (p Message_content_Future) RegisterAgentRequest() RegisterAgentRequest_Future {
	return RegisterAgentRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) RegisterAgentResponse() RegisterAgentResponse_Future {
	return RegisterAgentResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UnregisterAgentRequest() UnregisterAgentRequest_Future {
	return UnregisterAgentRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UnregisterAgentResponse() UnregisterAgentResponse_Future {
	return UnregisterAgentResponse_Future{Future: p.Future.Field(0, nil)}
}

type Envelope capnp.Struct

// Envelope_TypeID is the unique identifier for the type Envelope.
const Envelope_TypeID = 0xac586d10965c3f94

func NewEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func NewRootEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func ReadRootEnvelope(msg *capnp.Message) (Envelope, error) {
	root, err := msg.Root()
	return Envelope(root.Struct()), err
}

func (s Envelope) String() string {
	str, _ := text.Marshal(0xac586d10965c3f94, capnp.Struct(s))
	return str
}

func (s Envelope) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Envelope) DecodeFromPtr(p capnp.Ptr) Envelope {
	return Envelope(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Envelope) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Envelope) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Envelope) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Envelope) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Envelope) Subject() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Envelope) HasSubject() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Envelope) SubjectBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Envelope) SetSubject(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Envelope) Payload() (Message, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Message(p.Struct()), err
}

func (s Envelope) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Envelope) SetPayload(v Message) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPayload sets the payload field to a newly
// allocated Message struct, preferring placement in s's segment.
func (s Envelope) NewPayload() (Message, error) {
	ss, err := NewMessage(capnp.Struct(s).Segment())
	if err != nil {
		return Message{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Envelope_List is a list of Envelope.
type Envelope_List = capnp.StructList[Envelope]

// NewEnvelope creates a new list of Envelope.
func NewEnvelope_List(s *capnp.Segment, sz int32) (Envelope_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Envelope](l), err
}

// Envelope_Future is a wrapper for a Envelope promised by a client call.
type Envelope_Future struct{ *capnp.Future }

func (f Envelope_Future) Struct() (Envelope, error) {
	p, err := f.Future.Ptr()
	return Envelope(p.Struct()), err
}
func (p Envelope_Future) Payload() Message_Future {
	return Message_Future{Future: p.Future.Field(1, nil)}
}

const schema_d330108b08fd90db = "x\xda\xc4\x95_h\x1c\xd5\x17\xc7\xcf\xb9\xf7\xcel\x1f" +
	"\xb2\xc9,\x13~\xfc\xf0\xc1\x85\xa8X\x03.i\xe2S" +
	"\x10\xd6M\xbb\xa6\x11\x12\xf6\xeel\xb4)\x0a\xae\xbb\x97" +
	"\x10\xcd\xee\xcc\xce\xcc&]L\x1b\x8a\xdaTDi%" +
	"\x08}(\xa8X\xac\x7f\xc0R\xa8BP\xa9\xbe\x14A" +
	"A\xf1O$>\xe4\xc1\x87j\xb1H}\xd1\xa2\xdb\x91" +
	";\x99\xcdlf\x17\xad \xf86;|\xf6\x9c\xef=" +
	"\xdf\xef=3d\x92\xfb\xd8\x9e\xf8e\x15\x08\xcf)\xaa" +
	"\xf7\xf2\xe8\xbb\x976\x8e\xd1\xa3\x90\xe8e\xdew'\x9a" +
	"\xbb\x9e\xd3\x86\xbe\x04@}\x86^\xd1\x05\x8d\x01\x18\x8f" +
	"R\x8a\xc6<%\x08\xe0\x9d\xfeM;\x94\xcc\x1cx\x0a" +
	"\x12\xbd\x18\xe2\x0a\x89\x01\x8c\xd4\xe8\x00\xeaG\xe5_\xf4" +
	"\xc3t\x11\xd0\xfb>}\xf1\xec\xe0m\xcd\xd5n\xf0U" +
	":\x8cz\xd3\x87\xaf\xfb0\xfb\xff\xe7+\x9f4\x07O" +
	"\x01\xef\xc5v\x1a%2\xc7\xce\xeb5&\x9f*,\x0d" +
	"x\xe3\xc9#__:b\x9c\x8ej\xae\xb1\x0d\xfd\xb0" +
	"\xc4\x8cC\x8c\xa2\xf14\xf35_\x7f\xef\xd7O\xcb/" +
	"\xfc|\xa6k\xe5g\xd9\xab\xfaI\xbf\xf2\xf3L\xcaX" +
	"M?\xfc\x92V9\xf0v\x17\xcd\xfa\x8flM\xbf\xe6" +
	"\xb3W}\xb6\xef\xcc\xc1\x95\x95w\xf6~\xd0\x8d\x9dP" +
	"\xd6t\xae\xc8\xa7IE\xb2\xaf\xbd~\xeb\xa6}\xe2\xd8" +
	"z\xc7\x9c\xdfP\xae\xe8\x17$h\x9cS(\x1a\xef+" +
	"\xbe\xe6so\xbd\xa8\x7fxv\xe9\xdbHi)y\xe4" +
	"#e\x10\xf5/\xfc\xda\x9f)i@o\xf3\xd4\\\xfc" +
	"\xe2\xe8+\x9b\xdd`ToA=\xa1J8\xaeJ\xf8" +
	"N~\xb2\xb1\xfe\xd5\xe2\x0f\x1dB2\xea\x86>)A" +
	"c\xbfJ\xd1(\xa8\xbe\x90o.\xfc\xfe\xd3\x88\xb2~" +
	"\x0d\xf8\xff\xb0\xcd\xa4i\x8c!\x03\xd0g\xd4_\x00\xf5" +
	"G\xd4\xcb0\xe5\xcd\x16]\xb1Xl\xa4H\xa9hU" +
	"\xad\xd1R\xa5<]\xb5\xc5\xec\x9c\xd3\xe7\x0a\xbb\x90C" +
	"\xc4\x1e \xd8\x03\xb0\x07\x87\xd1\xbb\xff\x81\xd4x\xa6\x90" +
	"}\x88ffRw8\xa9\xbd\x93\xfbR\x99\xf1\xecT" +
	"A\xfe\x98\x9e\xcag\xc7\x93\x13F!\x9b\xdf\xaeJ\xb7" +
	"\xaa\xe6eAW\xd8\x99YQu\xf3\xc2\xb1\xccX\xd5" +
	"\x119D\xbe\x8b2\x00\x86\x00\x89\xbb\x0e\x02\xf0\xdd\x14" +
	"\xf9>\x82\x09\xc4~\x94/3\xc3\x00\xfc^\x8a|?" +
	"A\xcf\xb2MK\xd8\xee\x1cP\xe1`/`\x8e\"j" +
	"\xa1\x9f\x80\xf2eR\xd8\xb6i\xa3\x16\x06\x08\x105\xc0" +
	"\xa8\xa4\xe0\x94m\xa2\x92\x96\xf9\x9f\x89\xc2-Q\x93\"" +
	"\xe98\xc5Y_\x04\x93\"\x10C/\x13\xf11 \xcb" +
	"%\xb3\xea\x8a\xaa\x1b\xf5M,\xb8\xc1\x90i\xc4\xb5\x81" +
	"\x0e\xd7\xb2\x0f\x16B\xd7\xf2\xd9\xf1\x09#\xd6\xeeY\xa0" +
	"%k\xc7l\xd3\x8e\x8cc\x10\x80\xdfN\x91\x0f\x11l" +
	"M\xe3\xee\xb1`D\xf7\x10\xec+\x99e\x81\x0c\x082" +
	"\xc0\xe5\x8a\xf0\x0f\x13H\xe98l\xb6\x9a^\x10\xf3\xa6" +
	"\x15\x1d\xf9X\xd8#\xd1\xad\xc9\xb2S\x7f\xecqQr" +
	"[u\x97\xadbc\xde,\x96Q\x0b\x93\xde}\xbc9" +
	";\xed\x9b\xd5\x88t\x1c\xe8\xd6q8\xec\x18{B4" +
	"Z\xdd\x92\x0b\xc5\xf9z\xe7\x99B\x1b\xfe\xc1\xf5\xd9a" +
	"\xc4_\\\x9f\x8e\xac\xd6\xfa\xea\xc2q\xb7S\xe2\x9f\"" +
	".\xa3\xdaC\x91\xef\xbe\xd9T\xfe\xcd-\xad\xd5\x05\xfd" +
	"\x17\x9b\x84\x0b\xe6\xa6\x83\xbac\xbdt\x06\x95\xb4.\x8d" +
	"\x1f\xb3T\xc9L\xfaW\x83k\x94\xf5x\x9e\xaf\xb7\xf8" +
	"&\x00/S\xe4\x16\xc18\xde\xf0\xb6\xbc\xad\x9c\x07\xe0" +
	"\x16E\xbeD0N\x9a^?\x12\x80Dc\x0d\x80/" +
	"Q\xe4\xc7\x09\xc6\xe9\x1f^?R\x80\xc43\x1f\x03\xf0" +
	"\xe3\x14\xf9*A\xafe\x03\xee\xf0\x01\xb5p\x99\x07\xc1" +
	"\x8b\x82\xc1rA-\xfc\x16\x07d=\xf0\x16[sO" +
	"\xcb\xc1\xfbE\xb7?'\x11\x94\xb4/\xd2\xaa#\x00\xb5" +
	"\xf0\xab\xbd\xc5\xfe\x19\x00\x00\xff\xff\xf5;J/"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_d330108b08fd90db,
		Nodes: []uint64{
			0x810386dac7b63aa0,
			0x8358411f7810f89d,
			0x94fd232aa8c03fe3,
			0x992afdc987d01804,
			0x9d537ec7d57e7b00,
			0xa5ef8e64ccf7b7f9,
			0xac586d10965c3f94,
			0xbd43af87875aa50f,
			0xd7869072df1ea7a4,
			0xd87ca8be1392abb0,
			0xdfa13ac00d6999df,
			0xe877d4d779915127,
			0xf1d70533ecfbb5d6,
		},
		Compressed: true,
	})
}
