// Code generated by capnpc-go. DO NOT EDIT.

package agent

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Constants defined in agent.capnp.
const (
	ExitSuccess         = int64(0)
	ExitFailure         = int64(1)
	ExitCommandNotFound = int64(127)
	ExitInterrupted     = int64(130)
	CmdStartWorkerT     = "FJ.GATEWAY.%s.AGENT.%s.CMD.WORKER.%s.START"
	CmdStopWorkerT      = "FJ.GATEWAY.%s.AGENT.%s.CMD.WORKER.%s.STOP"
	CmdWriteStdinT      = "FJ.GATEWAY.%s.AGENT.%s.CMD.WORKER.%s.STDIN"
	EvtStartWorkerT     = "FJ.GATEWAY.%s.AGENT.%s.EVT.WORKER.%s.START"
	EvtStopWorkerT      = "FJ.GATEWAY.%s.AGENT.%s.EVT.WORKER.%s.STOP"
	EvtWorkerStatusT    = "FJ.GATEWAY.%s.AGENT.%s.EVT.WORKER.%s.STATUS"
	EvtWorkerStdoutT    = "FJ.GATEWAY.%s.AGENT.%s.EVT.WORKER.%s.STDOUT"
	EvtAgentInfoT       = "FJ.GATEWAY.%s.AGENT.%s.EVT.INFO"
)

type StartWorkerRequest capnp.Struct

// StartWorkerRequest_TypeID is the unique identifier for the type StartWorkerRequest.
const StartWorkerRequest_TypeID = 0x9892032ea4e69c6b

func NewStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func NewRootStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func ReadRootStartWorkerRequest(msg *capnp.Message) (StartWorkerRequest, error) {
	root, err := msg.Root()
	return StartWorkerRequest(root.Struct()), err
}

func (s StartWorkerRequest) String() string {
	str, _ := text.Marshal(0x9892032ea4e69c6b, capnp.Struct(s))
	return str
}

func (s StartWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerRequest) DecodeFromPtr(p capnp.Ptr) StartWorkerRequest {
	return StartWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerRequest) Command() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerRequest) HasCommand() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerRequest) CommandBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerRequest) SetCommand(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StartWorkerRequest) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasArgs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s StartWorkerRequest) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s StartWorkerRequest) Env() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasEnv() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s StartWorkerRequest) SetEnv(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewEnv sets the env field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewEnv(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// StartWorkerRequest_List is a list of StartWorkerRequest.
type StartWorkerRequest_List = capnp.StructList[StartWorkerRequest]

// NewStartWorkerRequest creates a new list of StartWorkerRequest.
func NewStartWorkerRequest_List(s *capnp.Segment, sz int32) (StartWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[StartWorkerRequest](l), err
}

// StartWorkerRequest_Future is a wrapper for a StartWorkerRequest promised by a client call.
type StartWorkerRequest_Future struct{ *capnp.Future }

func (f StartWorkerRequest_Future) Struct() (StartWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StartWorkerRequest(p.Struct()), err
}

type StartWorkerResponse capnp.Struct

// StartWorkerResponse_TypeID is the unique identifier for the type StartWorkerResponse.
const StartWorkerResponse_TypeID = 0xc5f4047bf39fa88d

func NewStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func NewRootStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func ReadRootStartWorkerResponse(msg *capnp.Message) (StartWorkerResponse, error) {
	root, err := msg.Root()
	return StartWorkerResponse(root.Struct()), err
}

func (s StartWorkerResponse) String() string {
	str, _ := text.Marshal(0xc5f4047bf39fa88d, capnp.Struct(s))
	return str
}

func (s StartWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerResponse) DecodeFromPtr(p capnp.Ptr) StartWorkerResponse {
	return StartWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StartWorkerResponse_List is a list of StartWorkerResponse.
type StartWorkerResponse_List = capnp.StructList[StartWorkerResponse]

// NewStartWorkerResponse creates a new list of StartWorkerResponse.
func NewStartWorkerResponse_List(s *capnp.Segment, sz int32) (StartWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StartWorkerResponse](l), err
}

// StartWorkerResponse_Future is a wrapper for a StartWorkerResponse promised by a client call.
type StartWorkerResponse_Future struct{ *capnp.Future }

func (f StartWorkerResponse_Future) Struct() (StartWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StartWorkerResponse(p.Struct()), err
}

type StopWorkerRequest capnp.Struct

// StopWorkerRequest_TypeID is the unique identifier for the type StopWorkerRequest.
const StopWorkerRequest_TypeID = 0xb15c44a86e45d3b0

func NewStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func NewRootStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func ReadRootStopWorkerRequest(msg *capnp.Message) (StopWorkerRequest, error) {
	root, err := msg.Root()
	return StopWorkerRequest(root.Struct()), err
}

func (s StopWorkerRequest) String() string {
	str, _ := text.Marshal(0xb15c44a86e45d3b0, capnp.Struct(s))
	return str
}

func (s StopWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerRequest) DecodeFromPtr(p capnp.Ptr) StopWorkerRequest {
	return StopWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// StopWorkerRequest_List is a list of StopWorkerRequest.
type StopWorkerRequest_List = capnp.StructList[StopWorkerRequest]

// NewStopWorkerRequest creates a new list of StopWorkerRequest.
func NewStopWorkerRequest_List(s *capnp.Segment, sz int32) (StopWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[StopWorkerRequest](l), err
}

// StopWorkerRequest_Future is a wrapper for a StopWorkerRequest promised by a client call.
type StopWorkerRequest_Future struct{ *capnp.Future }

func (f StopWorkerRequest_Future) Struct() (StopWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StopWorkerRequest(p.Struct()), err
}

type StopWorkerResponse capnp.Struct

// StopWorkerResponse_TypeID is the unique identifier for the type StopWorkerResponse.
const StopWorkerResponse_TypeID = 0xdea9ade321ec73b3

func NewStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func NewRootStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func ReadRootStopWorkerResponse(msg *capnp.Message) (StopWorkerResponse, error) {
	root, err := msg.Root()
	return StopWorkerResponse(root.Struct()), err
}

func (s StopWorkerResponse) String() string {
	str, _ := text.Marshal(0xdea9ade321ec73b3, capnp.Struct(s))
	return str
}

func (s StopWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerResponse) DecodeFromPtr(p capnp.Ptr) StopWorkerResponse {
	return StopWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StopWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StopWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StopWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StopWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StopWorkerResponse_List is a list of StopWorkerResponse.
type StopWorkerResponse_List = capnp.StructList[StopWorkerResponse]

// NewStopWorkerResponse creates a new list of StopWorkerResponse.
func NewStopWorkerResponse_List(s *capnp.Segment, sz int32) (StopWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StopWorkerResponse](l), err
}

// StopWorkerResponse_Future is a wrapper for a StopWorkerResponse promised by a client call.
type StopWorkerResponse_Future struct{ *capnp.Future }

func (f StopWorkerResponse_Future) Struct() (StopWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StopWorkerResponse(p.Struct()), err
}

type UpdateWorkerStatus capnp.Struct

// UpdateWorkerStatus_TypeID is the unique identifier for the type UpdateWorkerStatus.
const UpdateWorkerStatus_TypeID = 0xa62a70011c9fd5df

func NewUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func NewRootUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func ReadRootUpdateWorkerStatus(msg *capnp.Message) (UpdateWorkerStatus, error) {
	root, err := msg.Root()
	return UpdateWorkerStatus(root.Struct()), err
}

func (s UpdateWorkerStatus) String() string {
	str, _ := text.Marshal(0xa62a70011c9fd5df, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStatus) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStatus {
	return UpdateWorkerStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStatus) Status() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s UpdateWorkerStatus) SetStatus(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s UpdateWorkerStatus) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateWorkerStatus) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStatus) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateWorkerStatus) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// UpdateWorkerStatus_List is a list of UpdateWorkerStatus.
type UpdateWorkerStatus_List = capnp.StructList[UpdateWorkerStatus]

// NewUpdateWorkerStatus creates a new list of UpdateWorkerStatus.
func NewUpdateWorkerStatus_List(s *capnp.Segment, sz int32) (UpdateWorkerStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStatus](l), err
}

// UpdateWorkerStatus_Future is a wrapper for a UpdateWorkerStatus promised by a client call.
type UpdateWorkerStatus_Future struct{ *capnp.Future }

func (f UpdateWorkerStatus_Future) Struct() (UpdateWorkerStatus, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStatus(p.Struct()), err
}

type UpdateWorkerStdio capnp.Struct

// UpdateWorkerStdio_TypeID is the unique identifier for the type UpdateWorkerStdio.
const UpdateWorkerStdio_TypeID = 0xa76a3a9604a9e962

func NewUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func NewRootUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func ReadRootUpdateWorkerStdio(msg *capnp.Message) (UpdateWorkerStdio, error) {
	root, err := msg.Root()
	return UpdateWorkerStdio(root.Struct()), err
}

func (s UpdateWorkerStdio) String() string {
	str, _ := text.Marshal(0xa76a3a9604a9e962, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStdio) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStdio) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStdio {
	return UpdateWorkerStdio(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStdio) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStdio) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStdio) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStdio) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStdio) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s UpdateWorkerStdio) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStdio) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// UpdateWorkerStdio_List is a list of UpdateWorkerStdio.
type UpdateWorkerStdio_List = capnp.StructList[UpdateWorkerStdio]

// NewUpdateWorkerStdio creates a new list of UpdateWorkerStdio.
func NewUpdateWorkerStdio_List(s *capnp.Segment, sz int32) (UpdateWorkerStdio_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStdio](l), err
}

// UpdateWorkerStdio_Future is a wrapper for a UpdateWorkerStdio promised by a client call.
type UpdateWorkerStdio_Future struct{ *capnp.Future }

func (f UpdateWorkerStdio_Future) Struct() (UpdateWorkerStdio, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStdio(p.Struct()), err
}

type UpdateClientInfo capnp.Struct

// UpdateClientInfo_TypeID is the unique identifier for the type UpdateClientInfo.
const UpdateClientInfo_TypeID = 0xa073b10fb899cbb0

func NewUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func NewRootUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func ReadRootUpdateClientInfo(msg *capnp.Message) (UpdateClientInfo, error) {
	root, err := msg.Root()
	return UpdateClientInfo(root.Struct()), err
}

func (s UpdateClientInfo) String() string {
	str, _ := text.Marshal(0xa073b10fb899cbb0, capnp.Struct(s))
	return str
}

func (s UpdateClientInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateClientInfo) DecodeFromPtr(p capnp.Ptr) UpdateClientInfo {
	return UpdateClientInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateClientInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateClientInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateClientInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateClientInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateClientInfo) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateClientInfo) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateClientInfo) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UpdateClientInfo) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UpdateClientInfo) HasHostname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UpdateClientInfo) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetHostname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UpdateClientInfo) System() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UpdateClientInfo) HasSystem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UpdateClientInfo) SystemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetSystem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UpdateClientInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s UpdateClientInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s UpdateClientInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// UpdateClientInfo_List is a list of UpdateClientInfo.
type UpdateClientInfo_List = capnp.StructList[UpdateClientInfo]

// NewUpdateClientInfo creates a new list of UpdateClientInfo.
func NewUpdateClientInfo_List(s *capnp.Segment, sz int32) (UpdateClientInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[UpdateClientInfo](l), err
}

// UpdateClientInfo_Future is a wrapper for a UpdateClientInfo promised by a client call.
type UpdateClientInfo_Future struct{ *capnp.Future }

func (f UpdateClientInfo_Future) Struct() (UpdateClientInfo, error) {
	p, err := f.Future.Ptr()
	return UpdateClientInfo(p.Struct()), err
}

type Message capnp.Struct
type Message_content Message
type Message_content_Which uint16

const (
	Message_content_Which_startWorkerRequest  Message_content_Which = 0
	Message_content_Which_startWorkerResponse Message_content_Which = 1
	Message_content_Which_stopWorkerRequest   Message_content_Which = 2
	Message_content_Which_stopWorkerResponse  Message_content_Which = 3
	Message_content_Which_updateWorkerStatus  Message_content_Which = 4
	Message_content_Which_updateWorkerStdio   Message_content_Which = 5
	Message_content_Which_updateClientInfo    Message_content_Which = 6
)

func (w Message_content_Which) String() string {
	const s = "startWorkerRequeststartWorkerResponsestopWorkerRequeststopWorkerResponseupdateWorkerStatusupdateWorkerStdioupdateClientInfo"
	switch w {
	case Message_content_Which_startWorkerRequest:
		return s[0:18]
	case Message_content_Which_startWorkerResponse:
		return s[18:37]
	case Message_content_Which_stopWorkerRequest:
		return s[37:54]
	case Message_content_Which_stopWorkerResponse:
		return s[54:72]
	case Message_content_Which_updateWorkerStatus:
		return s[72:90]
	case Message_content_Which_updateWorkerStdio:
		return s[90:107]
	case Message_content_Which_updateClientInfo:
		return s[107:123]

	}
	return "Message_content_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xd270ea7f372f79cd

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xd270ea7f372f79cd, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Content() Message_content { return Message_content(s) }

func (s Message_content) Which() Message_content_Which {
	return Message_content_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_content) StartWorkerRequest() (StartWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != startWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStartWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerRequest(v StartWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerRequest sets the startWorkerRequest field to a newly
// allocated StartWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerRequest() (StartWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewStartWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StartWorkerResponse() (StartWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != startWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStartWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerResponse(v StartWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerResponse sets the startWorkerResponse field to a newly
// allocated StartWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerResponse() (StartWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewStartWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerRequest() (StopWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != stopWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStopWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerRequest(v StopWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerRequest sets the stopWorkerRequest field to a newly
// allocated StopWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerRequest() (StopWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewStopWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerResponse() (StopWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != stopWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStopWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerResponse(v StopWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerResponse sets the stopWorkerResponse field to a newly
// allocated StopWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerResponse() (StopWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewStopWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStatus() (UpdateWorkerStatus, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != updateWorkerStatus")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStatus(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStatus() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStatus(v UpdateWorkerStatus) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStatus sets the updateWorkerStatus field to a newly
// allocated UpdateWorkerStatus struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStatus() (UpdateWorkerStatus, error) {
	capnp.Struct(s).SetUint16(0, 4)
	ss, err := NewUpdateWorkerStatus(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStatus{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStdio() (UpdateWorkerStdio, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != updateWorkerStdio")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStdio(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStdio() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStdio(v UpdateWorkerStdio) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStdio sets the updateWorkerStdio field to a newly
// allocated UpdateWorkerStdio struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStdio() (UpdateWorkerStdio, error) {
	capnp.Struct(s).SetUint16(0, 5)
	ss, err := NewUpdateWorkerStdio(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStdio{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateClientInfo() (UpdateClientInfo, error) {
	if capnp.Struct(s).Uint16(0) != 6 {
		panic("Which() != updateClientInfo")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateClientInfo(p.Struct()), err
}

func (s Message_content) HasUpdateClientInfo() bool {
	if capnp.Struct(s).Uint16(0) != 6 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateClientInfo(v UpdateClientInfo) error {
	capnp.Struct(s).SetUint16(0, 6)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateClientInfo sets the updateClientInfo field to a newly
// allocated UpdateClientInfo struct, preferring placement in s's segment.
func (s Message_content) NewUpdateClientInfo() (UpdateClientInfo, error) {
	capnp.Struct(s).SetUint16(0, 6)
	ss, err := NewUpdateClientInfo(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateClientInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Content() Message_content_Future { return Message_content_Future{p.Future} }

// Message_content_Future is a wrapper for a Message_content promised by a client call.
type Message_content_Future struct{ *capnp.Future }

func (f Message_content_Future) Struct() (Message_content, error) {
	p, err := f.Future.Ptr()
	return Message_content(p.Struct()), err
}
func (p Message_content_Future) StartWorkerRequest() StartWorkerRequest_Future {
	return StartWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StartWorkerResponse() StartWorkerResponse_Future {
	return StartWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerRequest() StopWorkerRequest_Future {
	return StopWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerResponse() StopWorkerResponse_Future {
	return StopWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStatus() UpdateWorkerStatus_Future {
	return UpdateWorkerStatus_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStdio() UpdateWorkerStdio_Future {
	return UpdateWorkerStdio_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateClientInfo() UpdateClientInfo_Future {
	return UpdateClientInfo_Future{Future: p.Future.Field(0, nil)}
}

type Envelope capnp.Struct

// Envelope_TypeID is the unique identifier for the type Envelope.
const Envelope_TypeID = 0xf1d5f83d96db2344

func NewEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func NewRootEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func ReadRootEnvelope(msg *capnp.Message) (Envelope, error) {
	root, err := msg.Root()
	return Envelope(root.Struct()), err
}

func (s Envelope) String() string {
	str, _ := text.Marshal(0xf1d5f83d96db2344, capnp.Struct(s))
	return str
}

func (s Envelope) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Envelope) DecodeFromPtr(p capnp.Ptr) Envelope {
	return Envelope(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Envelope) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Envelope) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Envelope) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Envelope) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Envelope) Subject() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Envelope) HasSubject() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Envelope) SubjectBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Envelope) SetSubject(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Envelope) Payload() (Message, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Message(p.Struct()), err
}

func (s Envelope) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Envelope) SetPayload(v Message) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPayload sets the payload field to a newly
// allocated Message struct, preferring placement in s's segment.
func (s Envelope) NewPayload() (Message, error) {
	ss, err := NewMessage(capnp.Struct(s).Segment())
	if err != nil {
		return Message{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Envelope_List is a list of Envelope.
type Envelope_List = capnp.StructList[Envelope]

// NewEnvelope creates a new list of Envelope.
func NewEnvelope_List(s *capnp.Segment, sz int32) (Envelope_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Envelope](l), err
}

// Envelope_Future is a wrapper for a Envelope promised by a client call.
type Envelope_Future struct{ *capnp.Future }

func (f Envelope_Future) Struct() (Envelope, error) {
	p, err := f.Future.Ptr()
	return Envelope(p.Struct()), err
}
func (p Envelope_Future) Payload() Message_Future {
	return Message_Future{Future: p.Future.Field(1, nil)}
}

const schema_dcccaa5d36aa8b70 = "x\xda\xa4\x96}h\x14g\x1a\xc0\x9fg\xde\x99\x9d\xec" +
	"\xb1k\xb2\xcc\xde\x81 \x04\xf5\xee\xf0\x04\x13\xe3\xc7\x9d" +
	"\x0a!n\xbe$\x9e\xf9\x98\xdd\xe4r\x1e\x97\xc3\xc9\xee" +
	"k\\Mf6;3\xd1\xa0\x10\x14\x8e\x8b'\xe7\xa1" +
	"w\xd1\xcb!*R[\x0d\x16#\xad\xa0E\xff\xf0\xab" +
	"\x16ZA,\xfeQ\x1b-\xa4\xb55AKc\x15b" +
	"j:\xe5\x9d\xd9\x8f\xec\x07*\xe9\x7f3\xc3o~\xf3" +
	"<\xcf\xfb\xbc\xcf;K\xffK\xd6\xf2e^\xcb\x0d\x9c" +
	"l\x08.\xeb\xc9\xfa\x15\x17/\x9a\x0f\xf6\x81\xcf\xc3[" +
	"\xb1}C\xbfo\x1b\xfad\x04\x00\xa5\x87\xfc\xa84\xc1" +
	"\x8b\x00\xa1\xc7<\xc1\xd0$\xcf!\x805\xb0\x7f\xb8m" +
	"\x95\xb0\xf2@\x0e\x8e\xc2\x1d\xc9+0\xbc@ \x18\xf2" +
	"\x0b6\xbe\xfa\xc6\xcd\xc3\x0b\x87]\x039\xf8/\x85Q" +
	"i\xbe\x8d\xcfc\xf8\"\x07\xdfP\xbag/\xfd\xdb\xa6" +
	"C9x\x99pUZm\xe3+\x18\xbe\xd6\xc1\x17\x94" +
	"\xee,\xde\xbf\xfa\xda\xe1l|y\x99\xc0\xa1Tn\xf3" +
	"\xab\x18_\xed\xf0\xdb\x8e|\xfdV\x099\xf8?\xf0y" +
	"0\xcd\x0bD\x04\x90V\x0aSR\x80\xbd!\x95\x0bg" +
	"\x01\xad\xcd\xd1\xb6#\x13\xee3GsBy.\\\x95" +
	"\xa6m\xf5$S\xf3.[\xbd\xf0\xf9o\x9f|09" +
	"\x9c\x0f\x1f\x95\xd0\xc5\xf0\x97\x0c/p\xf0\xe1\x8f\x07/" +
	"\x14\x9e\xd3\x8fgE\xc2\xca-\xbd\x10\xc6%\x81\xbd!" +
	"\xa1\xeb\x1b@\xeb\x8b\xbb\xc7\xe6al\xf1\xdb {p" +
	"&\x8c\x0c\xb9\xef\x9a\x92\xc6l\xf8\xa1k;\xa0\xd5>" +
	"v\x9a?\xb4f\xeb;Yb\x9b\x0d\x88O\xa5z\x91" +
	"]\xd5\x89\x15\x80\xd6\xa5\xffhF\x7fy\xc3\xd9\x9c\x98" +
	"\xa3\xe2=\xc9d`(&\x12\x0c\xed\x12\x9d\x98?\xad" +
	"QOU\xff\xf5\\\xa6\xda\x0e\xf9\xef\xe2S\xe9\x80(" +
	"\x02\xb1|C\xadsO\x94\xd2\xf7A\xf6#Z\xb7z" +
	"K\xff\xd07\x1e\xbb\x03-(\xda!t\x89\xa3\x80\xcb" +
	"\xbb\xc5\x7f#\xa05\xb8\xf7\xa3%\xcbz\xaf]\xce]" +
	"m\xf7=\xa9\xdcm\xaf\x9e\x9b\xad\x9e\xdb\xfe\xfe\xbfN" +
	"\x1d\xfb~'\xff\xecF\x9e\xd4\x96\xd7\xbb9\x946\xb2" +
	"W\xa4\x167\xcb\xed\xe4\xa5\xe3\xfdG\xd7\x0d\xdc\xccq" +
	"\x9b\xeeqi\xb7\xed\xde\xc5\xdc\xfd\x8e;\x15h\xbe\x1a" +
	"\x1fp\x9f\x90\x06m\xf7\x80\xedn\x9c3\xb6\xbd|\xee" +
	"\x87#9\xeeA\xf7=\xe9\xa4\xed>\xce\xdcg\x1c\xf7" +
	"{\xfa\xe3\xf9_\xbe{\xfaA\xbe%9\xef\x9e\x92\xae" +
	"\xd8\xea\xcb\xb6\xfaW\xfd\xb5\xff\xf0\xefn\xff6G}" +
	"\xdf=.\x8d\xd9\xea\xaf\x98\xfa;G]\xbd\xf0\xf3C" +
	"\xe5\x93w'\xb2\xd4\x9c\xddF\xee!\x09\x7f\xc1\xae\xa6" +
	"\xdd\xdb\xa1\xc1R:\xa8j\x94\x84\x15.\xa6\xc6\xd6\xd0" +
	"\x1e#d(q\xa3U\x8bo\x13i\xbc\xb9\x09\x11=" +
	"\xc0\xa1\x07\xa0\x0c\xff\x82V\xed\xfa\x92u\x81\xe6\x9aV" +
	">\xb0\xb1\xe47zI`]MC3\xbb\xa8\xf9S" +
	"sIkc\xf0\x8f5Av\x17j\x0e\x90`s\x8e" +
	"9\xc0\xee\xeb\xd4\xcd\x1afz\xb9\xb4\xd7\x95\xc7[\xd7" +
	"P\xdb\x08I\x17S\x85\xbb\"\xb3\x0a\xb2\xaa\xbe\xfau" +
	"A\xee\x88\x1a\xb5J\xb4\xd3\x8cS`V\x018\x14\x90" +
	"U4\x89\x91$V\xa5uu)j\xa4A3j5" +
	"S\x8d\xcc\xc0\xfbf\xe0\xb65\x15,\x8d\x07+h\xb7" +
	"Iu\xa3\x09Q\xf6\x10\x1e\x80G\x00_M%\x80\xbc" +
	"\x96\xa0\xbc\x81C\x1f\xa2\x9f}\xd1W\xb7\x18@\xae&" +
	"(o\xe2\xd0\xc7q~\xe4\x00|m\x0b\x00\xe4?\x13" +
	"\x94\x0d\x0e\xfb\xc2N\x08\x89\xdc\xb1P\x89w\xe88\x07" +
	"\xb0\x898\xf5\x98\x03(R\xb5'\xebQn\xc6!3" +
	"\x1c\xa6\xba\x9eN!\x1fT\xa7\x1a4\x1e7c\xa2A" +
	"#\xe9\\\xf7d\xe7\xda\x12\x8b(\x06\xad\xea\x8cR\xd5" +
	"(dk\xcd2-Je\xaa\xac\x07\x907\x11\x94;" +
	"gd\x1ae\x0f\xb78I\xa52\xed^\x03 w\x12" +
	"\x94wp\xe8#\xc4\x8f\x04\xc0g\xb2B\xc5\x08\xca\xbb" +
	"8\xb4L\x9d\xc6U\xa5\x8b\x02@\xb2\x04\xd6\x16M7" +
	"\xb2\x9eU\xe8\xbd\xbaA\xbb\x92\xb7}J$\x12\xa7\xba" +
	"\x9ez%O\xf8\xceZU\x84\x0c\xc50u\x96@A" +
	"*\x81\xdf\xb1\xb0~MP^\xcaa2\xfe%\xcb\x00" +
	"\xe4E\x04\xe5\x15\x1cV\xe8\xf6K\xc9:\x16\xd3x\\" +
	"\x8b\xbf\xfe[\xc5!#\x12\xb5k\xc5\xa7>\xe5e\x0d" +
	"P@P\xf6sX\x18Q\x0c\x05\xbd\xc0\xa17gq" +
	"\xd8\x96\xd5b\xb6\x87dm\x86\xe0\x9b\xef\xd8Fl\xca" +
	"\xee\xda\x844\x1e\xa4\xc5\xc9\xa6\xcdD\xea\xa9\xae+\x1d" +
	"\xb4$\xac\xa9\x86HUC\x9eGx\x8fe\xd9\xd1\x9f" +
	"\xff?\x80|\x81\xa0|\x9dC/\xfeh9\xa5\xbar" +
	"\x02@\xbeNP\xbe\xcd\xa1\x97\x9b\xb6\x9c\xb5\xbeu\x10" +
	"@\xbeMP\x1e\xe1\xd0K^Z\xceb\x7f\xc6\x0c#" +
	"\x04\xe5G\x1cz\xf9\x1f,?\xf2\x00\xbe\x87\xec\xe9#" +
	"\x82\xf23\x0e\xbd\xc2\x94\xe5G\x01\xc07\xc1\x0c\xcf\x08" +
	"\x06\x91C\xaf\xeb\x85\xe5G\x17\x80o\xfa\x9f\x00A$" +
	"\x18\xf2\xb0\x19\xa3'\xb6!\xda)u\x9b\x94\xe8\x06\x16" +
	"\xa5\x0f\x7f@,\x82lL\x8fi\xa2\xaaS,J\x1f" +
	"3)\xce\xa9\x0f&l:2[\xea0\xccG\xe91" +
	"M%\xb6,5\xfb\x13\x98\x99\xe8\x05d\xf5f}G" +
	"L\x1d\x8b\xd2G|~,\x12E\x0d\x8b\xd2g{\x06" +
	"U\xd5\x89\xd1\xc4\xbc\x05`\x91%\x7f-\x12T\xc6J" +
	"\x86\xbb\"\xad\xf1\xa8A\x99\x93\xa8\xb3\x9e\xa8\xd5\xa4\xae" +
	"!sT\xce\x9c}v\xfe\xba=Yg\xb6\xf9\xb2t" +
	"\x9b\xbfj\xbb\xd0\x9e\x84'dD\x0a5\xd3\xc8\x0c\xb2" +
	"\xfd\xcd;\xbdZllI\xcf}L6\xb2\xa8t\xd0" +
	"Td\x88\xe9?\x16\x9f\xb7\x12\xb8>\xd6\xe3T5r" +
	"\xca6\x9b\xbd\x97]\xb6W\xee\xbd\x0a\xa7j?\xbbh" +
	"J\xa1a\xea\xb3.Z@ln\x09e\x16\xadF\xed" +
	"\xa1\x85\x9dZ\x8cfM\xc8\xca\xf4\x84L\x8d\xf8%\x95" +
	"\xe9\x11\xd9\xa7\x9b\xed[i\xd8HM\xe4\x98\xd2\xdb\xa9" +
	")\x11,J\xffn9=\xfaS\x00\x00\x00\xff\xff\xdf" +
	"b\x83\xb3"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_dcccaa5d36aa8b70,
		Nodes: []uint64{
			0x8bde75b9b9344aed,
			0x913505385db08e95,
			0x9506b02397c7c539,
			0x96605e6589822f4c,
			0x97c3398e1f7b2f22,
			0x9892032ea4e69c6b,
			0x9eac09f19c5d6966,
			0x9eb0f8baed26f523,
			0xa073b10fb899cbb0,
			0xa62a70011c9fd5df,
			0xa76a3a9604a9e962,
			0xaf4e3d88746f93bc,
			0xb15c44a86e45d3b0,
			0xb4652fa21957aa11,
			0xbdc379322dc88999,
			0xc5f4047bf39fa88d,
			0xc795479e88a0bca5,
			0xd270ea7f372f79cd,
			0xdcc6193d77e90e4f,
			0xdea9ade321ec73b3,
			0xee62811487468816,
			0xf1d5f83d96db2344,
		},
		Compressed: true,
	})
}
