// Code generated by capnpc-go. DO NOT EDIT.

package agent

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Constants defined in agent.capnp.
const (
	ExitSuccess         = int64(0)
	ExitFailure         = int64(1)
	ExitCommandNotFound = int64(127)
	ExitInterrupted     = int64(130)
	CmdStartWorkerT     = "FJ.AGENT.%s.CMD.WORKER.%s.START"
	CmdStopWorkerT      = "FJ.AGENT.%s.CMD.WORKER.%s.STOP"
	CmdWriteStdinT      = "FJ.AGENT.%s.CMD.WORKER.%s.STDIN"
	EvtStartWorkerT     = "FJ.AGENT.%s.EVT.WORKER.%s.START"
	EvtStopWorkerT      = "FJ.AGENT.%s.EVT.WORKER.%s.STOP"
	EvtWorkerStatusT    = "FJ.AGENT.%s.EVT.WORKER.%s.STATUS"
	EvtWorkerStdoutT    = "FJ.AGENT.%s.EVT.WORKER.%s.STDOUT"
	EvtAgentInfoT       = "FJ.AGENT.%s.EVT.INFO"
)

type StartWorkerRequest capnp.Struct

// StartWorkerRequest_TypeID is the unique identifier for the type StartWorkerRequest.
const StartWorkerRequest_TypeID = 0x9892032ea4e69c6b

func NewStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func NewRootStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func ReadRootStartWorkerRequest(msg *capnp.Message) (StartWorkerRequest, error) {
	root, err := msg.Root()
	return StartWorkerRequest(root.Struct()), err
}

func (s StartWorkerRequest) String() string {
	str, _ := text.Marshal(0x9892032ea4e69c6b, capnp.Struct(s))
	return str
}

func (s StartWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerRequest) DecodeFromPtr(p capnp.Ptr) StartWorkerRequest {
	return StartWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerRequest) Command() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerRequest) HasCommand() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerRequest) CommandBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerRequest) SetCommand(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StartWorkerRequest) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasArgs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s StartWorkerRequest) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s StartWorkerRequest) Env() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasEnv() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s StartWorkerRequest) SetEnv(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewEnv sets the env field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewEnv(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// StartWorkerRequest_List is a list of StartWorkerRequest.
type StartWorkerRequest_List = capnp.StructList[StartWorkerRequest]

// NewStartWorkerRequest creates a new list of StartWorkerRequest.
func NewStartWorkerRequest_List(s *capnp.Segment, sz int32) (StartWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[StartWorkerRequest](l), err
}

// StartWorkerRequest_Future is a wrapper for a StartWorkerRequest promised by a client call.
type StartWorkerRequest_Future struct{ *capnp.Future }

func (f StartWorkerRequest_Future) Struct() (StartWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StartWorkerRequest(p.Struct()), err
}

type StartWorkerResponse capnp.Struct

// StartWorkerResponse_TypeID is the unique identifier for the type StartWorkerResponse.
const StartWorkerResponse_TypeID = 0xc5f4047bf39fa88d

func NewStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func NewRootStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func ReadRootStartWorkerResponse(msg *capnp.Message) (StartWorkerResponse, error) {
	root, err := msg.Root()
	return StartWorkerResponse(root.Struct()), err
}

func (s StartWorkerResponse) String() string {
	str, _ := text.Marshal(0xc5f4047bf39fa88d, capnp.Struct(s))
	return str
}

func (s StartWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerResponse) DecodeFromPtr(p capnp.Ptr) StartWorkerResponse {
	return StartWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StartWorkerResponse_List is a list of StartWorkerResponse.
type StartWorkerResponse_List = capnp.StructList[StartWorkerResponse]

// NewStartWorkerResponse creates a new list of StartWorkerResponse.
func NewStartWorkerResponse_List(s *capnp.Segment, sz int32) (StartWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StartWorkerResponse](l), err
}

// StartWorkerResponse_Future is a wrapper for a StartWorkerResponse promised by a client call.
type StartWorkerResponse_Future struct{ *capnp.Future }

func (f StartWorkerResponse_Future) Struct() (StartWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StartWorkerResponse(p.Struct()), err
}

type StopWorkerRequest capnp.Struct

// StopWorkerRequest_TypeID is the unique identifier for the type StopWorkerRequest.
const StopWorkerRequest_TypeID = 0xb15c44a86e45d3b0

func NewStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func NewRootStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func ReadRootStopWorkerRequest(msg *capnp.Message) (StopWorkerRequest, error) {
	root, err := msg.Root()
	return StopWorkerRequest(root.Struct()), err
}

func (s StopWorkerRequest) String() string {
	str, _ := text.Marshal(0xb15c44a86e45d3b0, capnp.Struct(s))
	return str
}

func (s StopWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerRequest) DecodeFromPtr(p capnp.Ptr) StopWorkerRequest {
	return StopWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// StopWorkerRequest_List is a list of StopWorkerRequest.
type StopWorkerRequest_List = capnp.StructList[StopWorkerRequest]

// NewStopWorkerRequest creates a new list of StopWorkerRequest.
func NewStopWorkerRequest_List(s *capnp.Segment, sz int32) (StopWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[StopWorkerRequest](l), err
}

// StopWorkerRequest_Future is a wrapper for a StopWorkerRequest promised by a client call.
type StopWorkerRequest_Future struct{ *capnp.Future }

func (f StopWorkerRequest_Future) Struct() (StopWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StopWorkerRequest(p.Struct()), err
}

type StopWorkerResponse capnp.Struct

// StopWorkerResponse_TypeID is the unique identifier for the type StopWorkerResponse.
const StopWorkerResponse_TypeID = 0xdea9ade321ec73b3

func NewStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func NewRootStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func ReadRootStopWorkerResponse(msg *capnp.Message) (StopWorkerResponse, error) {
	root, err := msg.Root()
	return StopWorkerResponse(root.Struct()), err
}

func (s StopWorkerResponse) String() string {
	str, _ := text.Marshal(0xdea9ade321ec73b3, capnp.Struct(s))
	return str
}

func (s StopWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerResponse) DecodeFromPtr(p capnp.Ptr) StopWorkerResponse {
	return StopWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StopWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StopWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StopWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StopWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StopWorkerResponse_List is a list of StopWorkerResponse.
type StopWorkerResponse_List = capnp.StructList[StopWorkerResponse]

// NewStopWorkerResponse creates a new list of StopWorkerResponse.
func NewStopWorkerResponse_List(s *capnp.Segment, sz int32) (StopWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StopWorkerResponse](l), err
}

// StopWorkerResponse_Future is a wrapper for a StopWorkerResponse promised by a client call.
type StopWorkerResponse_Future struct{ *capnp.Future }

func (f StopWorkerResponse_Future) Struct() (StopWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StopWorkerResponse(p.Struct()), err
}

type UpdateWorkerStatus capnp.Struct

// UpdateWorkerStatus_TypeID is the unique identifier for the type UpdateWorkerStatus.
const UpdateWorkerStatus_TypeID = 0xa62a70011c9fd5df

func NewUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func NewRootUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func ReadRootUpdateWorkerStatus(msg *capnp.Message) (UpdateWorkerStatus, error) {
	root, err := msg.Root()
	return UpdateWorkerStatus(root.Struct()), err
}

func (s UpdateWorkerStatus) String() string {
	str, _ := text.Marshal(0xa62a70011c9fd5df, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStatus) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStatus {
	return UpdateWorkerStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStatus) Status() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s UpdateWorkerStatus) SetStatus(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s UpdateWorkerStatus) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateWorkerStatus) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStatus) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateWorkerStatus) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// UpdateWorkerStatus_List is a list of UpdateWorkerStatus.
type UpdateWorkerStatus_List = capnp.StructList[UpdateWorkerStatus]

// NewUpdateWorkerStatus creates a new list of UpdateWorkerStatus.
func NewUpdateWorkerStatus_List(s *capnp.Segment, sz int32) (UpdateWorkerStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStatus](l), err
}

// UpdateWorkerStatus_Future is a wrapper for a UpdateWorkerStatus promised by a client call.
type UpdateWorkerStatus_Future struct{ *capnp.Future }

func (f UpdateWorkerStatus_Future) Struct() (UpdateWorkerStatus, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStatus(p.Struct()), err
}

type UpdateWorkerStdio capnp.Struct

// UpdateWorkerStdio_TypeID is the unique identifier for the type UpdateWorkerStdio.
const UpdateWorkerStdio_TypeID = 0xa76a3a9604a9e962

func NewUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func NewRootUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func ReadRootUpdateWorkerStdio(msg *capnp.Message) (UpdateWorkerStdio, error) {
	root, err := msg.Root()
	return UpdateWorkerStdio(root.Struct()), err
}

func (s UpdateWorkerStdio) String() string {
	str, _ := text.Marshal(0xa76a3a9604a9e962, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStdio) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStdio) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStdio {
	return UpdateWorkerStdio(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStdio) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStdio) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStdio) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStdio) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStdio) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s UpdateWorkerStdio) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStdio) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// UpdateWorkerStdio_List is a list of UpdateWorkerStdio.
type UpdateWorkerStdio_List = capnp.StructList[UpdateWorkerStdio]

// NewUpdateWorkerStdio creates a new list of UpdateWorkerStdio.
func NewUpdateWorkerStdio_List(s *capnp.Segment, sz int32) (UpdateWorkerStdio_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStdio](l), err
}

// UpdateWorkerStdio_Future is a wrapper for a UpdateWorkerStdio promised by a client call.
type UpdateWorkerStdio_Future struct{ *capnp.Future }

func (f UpdateWorkerStdio_Future) Struct() (UpdateWorkerStdio, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStdio(p.Struct()), err
}

type UpdateClientInfo capnp.Struct

// UpdateClientInfo_TypeID is the unique identifier for the type UpdateClientInfo.
const UpdateClientInfo_TypeID = 0xa073b10fb899cbb0

func NewUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func NewRootUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func ReadRootUpdateClientInfo(msg *capnp.Message) (UpdateClientInfo, error) {
	root, err := msg.Root()
	return UpdateClientInfo(root.Struct()), err
}

func (s UpdateClientInfo) String() string {
	str, _ := text.Marshal(0xa073b10fb899cbb0, capnp.Struct(s))
	return str
}

func (s UpdateClientInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateClientInfo) DecodeFromPtr(p capnp.Ptr) UpdateClientInfo {
	return UpdateClientInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateClientInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateClientInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateClientInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateClientInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateClientInfo) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateClientInfo) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateClientInfo) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UpdateClientInfo) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UpdateClientInfo) HasHostname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UpdateClientInfo) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetHostname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UpdateClientInfo) System() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UpdateClientInfo) HasSystem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UpdateClientInfo) SystemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetSystem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UpdateClientInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s UpdateClientInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s UpdateClientInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// UpdateClientInfo_List is a list of UpdateClientInfo.
type UpdateClientInfo_List = capnp.StructList[UpdateClientInfo]

// NewUpdateClientInfo creates a new list of UpdateClientInfo.
func NewUpdateClientInfo_List(s *capnp.Segment, sz int32) (UpdateClientInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[UpdateClientInfo](l), err
}

// UpdateClientInfo_Future is a wrapper for a UpdateClientInfo promised by a client call.
type UpdateClientInfo_Future struct{ *capnp.Future }

func (f UpdateClientInfo_Future) Struct() (UpdateClientInfo, error) {
	p, err := f.Future.Ptr()
	return UpdateClientInfo(p.Struct()), err
}

type Message capnp.Struct
type Message_content Message
type Message_content_Which uint16

const (
	Message_content_Which_startWorkerRequest  Message_content_Which = 0
	Message_content_Which_startWorkerResponse Message_content_Which = 1
	Message_content_Which_stopWorkerRequest   Message_content_Which = 2
	Message_content_Which_stopWorkerResponse  Message_content_Which = 3
	Message_content_Which_updateWorkerStatus  Message_content_Which = 4
	Message_content_Which_updateWorkerStdio   Message_content_Which = 5
	Message_content_Which_updateClientInfo    Message_content_Which = 6
)

func (w Message_content_Which) String() string {
	const s = "startWorkerRequeststartWorkerResponsestopWorkerRequeststopWorkerResponseupdateWorkerStatusupdateWorkerStdioupdateClientInfo"
	switch w {
	case Message_content_Which_startWorkerRequest:
		return s[0:18]
	case Message_content_Which_startWorkerResponse:
		return s[18:37]
	case Message_content_Which_stopWorkerRequest:
		return s[37:54]
	case Message_content_Which_stopWorkerResponse:
		return s[54:72]
	case Message_content_Which_updateWorkerStatus:
		return s[72:90]
	case Message_content_Which_updateWorkerStdio:
		return s[90:107]
	case Message_content_Which_updateClientInfo:
		return s[107:123]

	}
	return "Message_content_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xd270ea7f372f79cd

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xd270ea7f372f79cd, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Content() Message_content { return Message_content(s) }

func (s Message_content) Which() Message_content_Which {
	return Message_content_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_content) StartWorkerRequest() (StartWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != startWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStartWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerRequest(v StartWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerRequest sets the startWorkerRequest field to a newly
// allocated StartWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerRequest() (StartWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewStartWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StartWorkerResponse() (StartWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != startWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStartWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerResponse(v StartWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerResponse sets the startWorkerResponse field to a newly
// allocated StartWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerResponse() (StartWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewStartWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerRequest() (StopWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != stopWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStopWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerRequest(v StopWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerRequest sets the stopWorkerRequest field to a newly
// allocated StopWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerRequest() (StopWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewStopWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerResponse() (StopWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != stopWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStopWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerResponse(v StopWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerResponse sets the stopWorkerResponse field to a newly
// allocated StopWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerResponse() (StopWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewStopWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStatus() (UpdateWorkerStatus, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != updateWorkerStatus")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStatus(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStatus() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStatus(v UpdateWorkerStatus) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStatus sets the updateWorkerStatus field to a newly
// allocated UpdateWorkerStatus struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStatus() (UpdateWorkerStatus, error) {
	capnp.Struct(s).SetUint16(0, 4)
	ss, err := NewUpdateWorkerStatus(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStatus{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStdio() (UpdateWorkerStdio, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != updateWorkerStdio")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStdio(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStdio() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStdio(v UpdateWorkerStdio) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStdio sets the updateWorkerStdio field to a newly
// allocated UpdateWorkerStdio struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStdio() (UpdateWorkerStdio, error) {
	capnp.Struct(s).SetUint16(0, 5)
	ss, err := NewUpdateWorkerStdio(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStdio{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateClientInfo() (UpdateClientInfo, error) {
	if capnp.Struct(s).Uint16(0) != 6 {
		panic("Which() != updateClientInfo")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateClientInfo(p.Struct()), err
}

func (s Message_content) HasUpdateClientInfo() bool {
	if capnp.Struct(s).Uint16(0) != 6 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateClientInfo(v UpdateClientInfo) error {
	capnp.Struct(s).SetUint16(0, 6)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateClientInfo sets the updateClientInfo field to a newly
// allocated UpdateClientInfo struct, preferring placement in s's segment.
func (s Message_content) NewUpdateClientInfo() (UpdateClientInfo, error) {
	capnp.Struct(s).SetUint16(0, 6)
	ss, err := NewUpdateClientInfo(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateClientInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Content() Message_content_Future { return Message_content_Future{p.Future} }

// Message_content_Future is a wrapper for a Message_content promised by a client call.
type Message_content_Future struct{ *capnp.Future }

func (f Message_content_Future) Struct() (Message_content, error) {
	p, err := f.Future.Ptr()
	return Message_content(p.Struct()), err
}
func (p Message_content_Future) StartWorkerRequest() StartWorkerRequest_Future {
	return StartWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StartWorkerResponse() StartWorkerResponse_Future {
	return StartWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerRequest() StopWorkerRequest_Future {
	return StopWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerResponse() StopWorkerResponse_Future {
	return StopWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStatus() UpdateWorkerStatus_Future {
	return UpdateWorkerStatus_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStdio() UpdateWorkerStdio_Future {
	return UpdateWorkerStdio_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateClientInfo() UpdateClientInfo_Future {
	return UpdateClientInfo_Future{Future: p.Future.Field(0, nil)}
}

type Envelope capnp.Struct

// Envelope_TypeID is the unique identifier for the type Envelope.
const Envelope_TypeID = 0xf1d5f83d96db2344

func NewEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func NewRootEnvelope(s *capnp.Segment) (Envelope, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Envelope(st), err
}

func ReadRootEnvelope(msg *capnp.Message) (Envelope, error) {
	root, err := msg.Root()
	return Envelope(root.Struct()), err
}

func (s Envelope) String() string {
	str, _ := text.Marshal(0xf1d5f83d96db2344, capnp.Struct(s))
	return str
}

func (s Envelope) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Envelope) DecodeFromPtr(p capnp.Ptr) Envelope {
	return Envelope(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Envelope) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Envelope) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Envelope) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Envelope) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Envelope) Subject() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Envelope) HasSubject() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Envelope) SubjectBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Envelope) SetSubject(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Envelope) Payload() (Message, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return Message(p.Struct()), err
}

func (s Envelope) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Envelope) SetPayload(v Message) error {
	return capnp.Struct(s).SetPtr(1, capnp.Struct(v).ToPtr())
}

// NewPayload sets the payload field to a newly
// allocated Message struct, preferring placement in s's segment.
func (s Envelope) NewPayload() (Message, error) {
	ss, err := NewMessage(capnp.Struct(s).Segment())
	if err != nil {
		return Message{}, err
	}
	err = capnp.Struct(s).SetPtr(1, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Envelope_List is a list of Envelope.
type Envelope_List = capnp.StructList[Envelope]

// NewEnvelope creates a new list of Envelope.
func NewEnvelope_List(s *capnp.Segment, sz int32) (Envelope_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Envelope](l), err
}

// Envelope_Future is a wrapper for a Envelope promised by a client call.
type Envelope_Future struct{ *capnp.Future }

func (f Envelope_Future) Struct() (Envelope, error) {
	p, err := f.Future.Ptr()
	return Envelope(p.Struct()), err
}
func (p Envelope_Future) Payload() Message_Future {
	return Message_Future{Future: p.Future.Field(1, nil)}
}

const schema_dcccaa5d36aa8b70 = "x\xda\xa4\x96kl\x14\xd7\x15\xc7\xcf\x99\xbb\xb3\xc3T" +
	"\xbb\xec\xaef\xa9\x84d\xe4\xf2\xaa0\xaam\x9emA" +
	"B\xc6Od\x0a\xb6g\xd7\xae\xf9\x80+\x06\xef\xc5," +
	"\xd83\xeby\x18[\xb4\xb2\x8aZ\x01EPA\x05\x94" +
	"\x0a\x01B}\x80U\x84Q\x88\x04\x11\x91\x12\x1e!(" +
	"A\"D|\x08\xb1\x88\xe2\x84\x04,\x1c\xc5\xc4\x91\xc0" +
	"\x09\x99\xe8\xce\xec\xcb\xbb\x1b \xca\xb7\x99\xd1\x7f~\xf7" +
	"\x7f\xce=\xe7\xdc\xbb`'Y\xe9Y\xe8\xb7E\xe0d" +
	"\x93\xf7\xda\xa3\xab\x97\\\xbch\xdd\xdb\x03!\x9f\xc7N" +
	"\xec\x19\xf8u\xdb\xc0\xbbC\x00(\xdd\xf7\x0cKc\x1e" +
	"\x01 \xfa\xc8C0\xfa\xc4\xc3!\x80}p\xdf`\xdb" +
	"o\xf9\xa5\xfb\xf3\xe4O=\xb7%\x9e\x17\x00\"<\xc1" +
	"\xa8\x8fw\xd4\xcb\xae]?<{\xd0{0O-\xf2" +
	"\xc3\xd24\xa6\x8e\x06\x99\xbc\xc8\x95\xaf)\xdf\xb1\x9b\xfe" +
	"a\xc3\xa1<\xf9\x0c\xfe\xb24\xd7\x91\xff\x82\xc9\x7f\xe5" +
	"\xcag\x95o/\xde\xb7\xec\xca\xe1\\\xf9\xe2\x19<\x87" +
	"R\x89\xa3\x9f\xc3\xf4\x0b\\\xfd\xd6\xa3\x9f\xfd\xbb\x8c\x1c" +
	"\xf8'\x84|\x98\xd1\xf3D\x00\x90f\xf2\x13R)\xfb" +
	"C*\xe1\xcf\x02\xda\x9b\xe2mG\xc7\xc4\xff\x1f\xcb\xb3" +
	"\xf21\x7fYz\xe8\xa0?e\xe8/]\xf4\xec\xaf\x7f" +
	"9\xfa\xda\x93\xc1B\xf2ai\xd4\x91?`\xf2qW" +
	">\xf8\xce\x91\x0b\x81s\xc6\x89\x1c',\xdb\xd2}~" +
	"D\x1as\x9c\x8c\xf2\x9f\x03\xda\x1f\xdd9^\x84\x89\xf9" +
	"\xff\x05\xd9\x87\xd9bd\x92\x1b\xde\x09\xe9\x8e\x97=\xbd" +
	"\xe7\xdd\x06ho|x\xdash\xf9\x96\xff\xe5\x80\x1d" +
	"m\xa9\xf0XZ&\xb0\xa7\xa5B\x05\xa0}\xe9\x1f\x9a" +
	"\xb9kE\xc3\xd9<\xcf-\xc2]Ia\xc2\xe8z\x81" +
	"`t\xb3\xe0z~\xbfV=U\xb3\xfe\xdcd\xb4c" +
	"9.<\x96,A\x00b\x87\x06Z\xa7\x9f,\xa7\xe7" +
	"A\x0e#\xda7\xfb\xca\x7f\xd3?\x92\xb8\x0d-(8" +
	"\x16da\x18pq\x8b\xf0w\x04\xb4\x8f\xec~\xbbt" +
	"Q\xdf\x95\xd7\xf3\xd6\x9f&\xde\x95f\x8al\xfd\"\x91" +
	"`t\x9e\xe8\xac\xbf\xf7\xd4\xf1\xaf\xb6{\xc6\xaf\x15\x08" +
	"mq\x89\xc8\xa1\xb4\x94\xfd\"-\x14Yl\xff\xb9t" +
	"b\xd7\xb1U\x07\xaf\xe7\xb1eqDjs\xd8\xeb\x18" +
	";\xe6\xb2\xd3F\x0b\xe58.\x9e\x94\xba\x1dv\x97\xc3" +
	"n\x9c\xfap\xdb\x8a\xe9o\x0d\xe5\xb1\xbb\xc5\xbb\xd2\x9f" +
	"\x1cv/c\xff\xc5e\xbfb<\x9a\xf9\xc9\x99\xd3\xf7" +
	"\x0am\xc9_\xc5\x09i\xbf\x83\xde\xeb\xa0\x7f\xbe\xabn" +
	"g\xf8\xcf\x1b\xbf\xc8C\x9f\x11G\xa4\x8b\x0e\xfa<C" +
	"\xbf\xe1\xa2kf\x7fxh\xc5\x93;c9h\x8e\x01" +
	"\xaf\x89\x03\xd2M\x07}C\xdc\x06\x0d\xb6\xd2AU\xb3" +
	"\xac]\xe1\x12jb9\xed1\xa3\xa6\xa2\x9b\xad\x9a\xbe" +
	"U\xa0zs\x13\"\xfa\x80C\x1f\xc0B\xe4\xd0\xae[" +
	"]V\xb9\xaa\xb6\xa1\xd9[6\xd7(\xab\xfd}sY" +
	"kc\xe4w\xb5\x11\xf6\x16m\xae\x8c4C\x8a\x96\x84" +
	"U\xb2\xd7zu\x93\x86\xd9\xa8\x10\x0e\xa4I\x98\"\x05" +
	"\xea\x1b\xea\x1a'\xbbi\xef\x8a\xbd\xbc\x9b\xea\xb55\xcf" +
	"w\xd3\x1b7\xeb\x94x\xa7\xa5S` \x1e8\xe4\x91" +
	"e+\xa5\")Y\xb5\xd6\xd5\xa5\xa8\xb1\x06\xcd\xac\xd3" +
	",5\x96%\xef\xcf\x92;\x16\xd3\xfe\xa8\x1e\xa9\xa0\xdd" +
	"\x165\xcc&D\xd9G<\x00\x1e\x04\x08\xd5V\x01\xc8" +
	"+\x09\xcak8\x0c!\x86\xd9\x8a\xa1\xfa\xf9\x00r\x0d" +
	"Ay\x03\x87!\x8e\x0b#\x07\x10j\x9b\x05 \xaf#" +
	"(\x9b\x1c\xf6\xb7\xbb\x16\x92\xe1b@\xd1;\x0c\x9c\x0a" +
	"\xd8D\xdc\x14L\x05\x14\xa8\xda\x93\xf3)g3{\xe3" +
	"f\xd4jo\xa7\x86\x91\x09\xa1\x90\xa8^5\xa9\xae[" +
	"\x09\xc1\xa4\xb1L\xac;rcmI\xc4\x14\x93Vw" +
	"\xc6\xa9j\x06\xd8\xa6\xb2H\x83\xe9H\x95\xd5\x00\xf2\x06" +
	"\x82rgV\xa4q\xf6q\xb3\x1bT:\xd2\xee\xe5\x00" +
	"r'A\xb9\x97\xc3\x10!a$\x00!\x8b%*A" +
	"P\xfe#\x87\xb6eP]U\xba(\x00\xa4R`o" +
	"\xd6\x0c3\xe7[\x85\xd1g\x98\xb4+\xf5\xda\xaf\xc4b" +
	":5\x8c\xf4/\x05\xec\xbb{U\x115\x15\xd32X" +
	"\x00S\xd2\x01\x940[s\x08\xca\x0b8L\xf9/]" +
	"\x04 \xcf#(/\xe1\xb0\xc2p~J\xe5\xb1\x98\xea" +
	"\xba\xa6\xbfx\xad\xe2\xa8\x19\x8b;\xb9\xf2\xa4\x97\xf2\xb3" +
	"\x02\x98BP\x0es\x18\x88)\xa6\x82~\xe0\xd0\x9f\xb7" +
	"9\xac\x1d\xb5\x84\xc3!\xfa\xe4\x16\x9aH\x97?\x97\xdb" +
	"\x8c\x15\xac\xfe\x1b\x9br+5\x09\xd2#\xb48U\xa8" +
	"\x93%k\xa9a(\x1d\xb4\xac]SM\x81\xaa\xa6\\" +
	"D<>\xdbv\x1c\xbf\xfa/\x00\xf9\x02A\xf9*\x87" +
	"~\xfc\xcev\xd3\xf3\xe6I\x00\xf9*A\xf9\x16\x87~" +
	"\xee\x99\xed\xee\xef\xcd\x03\x00\xf2-\x82\xf2\x10\x87~\xf2" +
	"\xad\xedn\xf0\x07\x8c0DP~\xc0\xa1\xdf\xf3\x8d\x1d" +
	"F\x0f@\xe8>\xfb\xfa\x80\xa0<\xce\xa1\x9f\x9f\xb0\xc3" +
	"\xc8\x03\x84\xc6\x18a\x9c`\x049\xf4{\x9f\xdaa\xf4" +
	"\x02\x84\x9e\xfd\x0d \x82\xec\x16\xc1\xba\xdfH\xb6\x1e:" +
	"!u[\x94\x18&\x063\x879 \x06!Wf$" +
	"4A5(\x063\xc7FZ\xe7\xe6\x07\x934\x03\x19" +
	"-}\xb8\x15R\x19\x09M%\x0e,=\xcb\x932+" +
	"\xb9\xff\xc8\xf2\xcdj\x8dX\x06\x063GvaY," +
	"\x8e\x1a\x063g\xf5$Uu'\xc6\x93\xc3\x14\x809" +
	"K]\x15\x92\xaa\xdc\xc9\xd9\xaa\xc7M\xca\x98D\xfd\xc1" +
	"\xc1)\x14\x1a\x9c5\xf5\x0d\x93\x06g\xf6\x88sB6" +
	"\x9c\x01\x9a]\xcd\x8b2\xd5\xfc\xbc\xae\xa0=IN\xd4" +
	"\x8c\x054\xcb\x9c\xec\xebg\x19_\xa4\xd0\xf1R\xd3\xd8" +
	"\xd2\x9c5\x920U\xb1\x82\xd2A\xd3~\x103W\x8d" +
	"\x90\xbf\x0a\xb8~V\xccT5\x0b\x9c,/\xd7X\xd9" +
	"\xe9yacU\xb8\xf9\xf9\xc9\xe9Q\x02\xa6e\xfc\xb8" +
	"\xf4T6\xb7Ds\xd3S\xab\xf6\xd0@\xa7\x96\xa09" +
	"\x83\xae*3\xe8\xd2\x93\xba\xb4*3\xe9\xfa\x0dk\xe3" +
	"\x16\xdan\xa6\x07kB\xe9\xeb\xd4\x94\x18\x0637\"" +
	"\xb7\xec\xbe\x0f\x00\x00\xff\xff\x14Si\x08"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_dcccaa5d36aa8b70,
		Nodes: []uint64{
			0x8bde75b9b9344aed,
			0x913505385db08e95,
			0x9506b02397c7c539,
			0x96605e6589822f4c,
			0x97c3398e1f7b2f22,
			0x9892032ea4e69c6b,
			0x9eac09f19c5d6966,
			0x9eb0f8baed26f523,
			0xa073b10fb899cbb0,
			0xa62a70011c9fd5df,
			0xa76a3a9604a9e962,
			0xaf4e3d88746f93bc,
			0xb15c44a86e45d3b0,
			0xb4652fa21957aa11,
			0xbdc379322dc88999,
			0xc5f4047bf39fa88d,
			0xc795479e88a0bca5,
			0xd270ea7f372f79cd,
			0xdcc6193d77e90e4f,
			0xdea9ade321ec73b3,
			0xee62811487468816,
			0xf1d5f83d96db2344,
		},
		Compressed: true,
	})
}
