// Code generated by capnpc-go. DO NOT EDIT.

package agent

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

// Constants defined in agent.capnp.
const (
	ExitSuccess         = int64(0)
	ExitFailure         = int64(1)
	ExitCommandNotFound = int64(127)
	CmdStartWorkerT     = "FJ.AGENT.%s.CMD.WORKER.%s.START"
	CmdStopWorkerT      = "FJ.AGENT.%s.CMD.WORKER.%s.STOP"
	CmdWriteStdinT      = "FJ.AGENT.%s.CMD.WORKER.%s.STDIN"
	EvtStartWorkerT     = "FJ.AGENT.%s.EVT.WORKER.%s.START"
	EvtStopWorkerT      = "FJ.AGENT.%s.EVT.WORKER.%s.STOP"
	EvtWorkerStatusT    = "FJ.AGENT.%s.EVT.WORKER.%s.STATUS"
	EvtWorkerStdoutT    = "FJ.AGENT.%s.EVT.WORKER.%s.STDOUT"
	EvtAgentInfoT       = "FJ.AGENT.%s.EVT.INFO"
)

type StartWorkerRequest capnp.Struct

// StartWorkerRequest_TypeID is the unique identifier for the type StartWorkerRequest.
const StartWorkerRequest_TypeID = 0x9892032ea4e69c6b

func NewStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func NewRootStartWorkerRequest(s *capnp.Segment) (StartWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return StartWorkerRequest(st), err
}

func ReadRootStartWorkerRequest(msg *capnp.Message) (StartWorkerRequest, error) {
	root, err := msg.Root()
	return StartWorkerRequest(root.Struct()), err
}

func (s StartWorkerRequest) String() string {
	str, _ := text.Marshal(0x9892032ea4e69c6b, capnp.Struct(s))
	return str
}

func (s StartWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerRequest) DecodeFromPtr(p capnp.Ptr) StartWorkerRequest {
	return StartWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerRequest) Command() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerRequest) HasCommand() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerRequest) CommandBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerRequest) SetCommand(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s StartWorkerRequest) Args() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasArgs() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s StartWorkerRequest) SetArgs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewArgs sets the args field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewArgs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s StartWorkerRequest) Env() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s StartWorkerRequest) HasEnv() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s StartWorkerRequest) SetEnv(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewEnv sets the env field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s StartWorkerRequest) NewEnv(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// StartWorkerRequest_List is a list of StartWorkerRequest.
type StartWorkerRequest_List = capnp.StructList[StartWorkerRequest]

// NewStartWorkerRequest creates a new list of StartWorkerRequest.
func NewStartWorkerRequest_List(s *capnp.Segment, sz int32) (StartWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[StartWorkerRequest](l), err
}

// StartWorkerRequest_Future is a wrapper for a StartWorkerRequest promised by a client call.
type StartWorkerRequest_Future struct{ *capnp.Future }

func (f StartWorkerRequest_Future) Struct() (StartWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StartWorkerRequest(p.Struct()), err
}

type StartWorkerResponse capnp.Struct

// StartWorkerResponse_TypeID is the unique identifier for the type StartWorkerResponse.
const StartWorkerResponse_TypeID = 0xc5f4047bf39fa88d

func NewStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func NewRootStartWorkerResponse(s *capnp.Segment) (StartWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StartWorkerResponse(st), err
}

func ReadRootStartWorkerResponse(msg *capnp.Message) (StartWorkerResponse, error) {
	root, err := msg.Root()
	return StartWorkerResponse(root.Struct()), err
}

func (s StartWorkerResponse) String() string {
	str, _ := text.Marshal(0xc5f4047bf39fa88d, capnp.Struct(s))
	return str
}

func (s StartWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StartWorkerResponse) DecodeFromPtr(p capnp.Ptr) StartWorkerResponse {
	return StartWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StartWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StartWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StartWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StartWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StartWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StartWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StartWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StartWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StartWorkerResponse_List is a list of StartWorkerResponse.
type StartWorkerResponse_List = capnp.StructList[StartWorkerResponse]

// NewStartWorkerResponse creates a new list of StartWorkerResponse.
func NewStartWorkerResponse_List(s *capnp.Segment, sz int32) (StartWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StartWorkerResponse](l), err
}

// StartWorkerResponse_Future is a wrapper for a StartWorkerResponse promised by a client call.
type StartWorkerResponse_Future struct{ *capnp.Future }

func (f StartWorkerResponse_Future) Struct() (StartWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StartWorkerResponse(p.Struct()), err
}

type StopWorkerRequest capnp.Struct

// StopWorkerRequest_TypeID is the unique identifier for the type StopWorkerRequest.
const StopWorkerRequest_TypeID = 0xb15c44a86e45d3b0

func NewStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func NewRootStopWorkerRequest(s *capnp.Segment) (StopWorkerRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return StopWorkerRequest(st), err
}

func ReadRootStopWorkerRequest(msg *capnp.Message) (StopWorkerRequest, error) {
	root, err := msg.Root()
	return StopWorkerRequest(root.Struct()), err
}

func (s StopWorkerRequest) String() string {
	str, _ := text.Marshal(0xb15c44a86e45d3b0, capnp.Struct(s))
	return str
}

func (s StopWorkerRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerRequest) DecodeFromPtr(p capnp.Ptr) StopWorkerRequest {
	return StopWorkerRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// StopWorkerRequest_List is a list of StopWorkerRequest.
type StopWorkerRequest_List = capnp.StructList[StopWorkerRequest]

// NewStopWorkerRequest creates a new list of StopWorkerRequest.
func NewStopWorkerRequest_List(s *capnp.Segment, sz int32) (StopWorkerRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[StopWorkerRequest](l), err
}

// StopWorkerRequest_Future is a wrapper for a StopWorkerRequest promised by a client call.
type StopWorkerRequest_Future struct{ *capnp.Future }

func (f StopWorkerRequest_Future) Struct() (StopWorkerRequest, error) {
	p, err := f.Future.Ptr()
	return StopWorkerRequest(p.Struct()), err
}

type StopWorkerResponse capnp.Struct

// StopWorkerResponse_TypeID is the unique identifier for the type StopWorkerResponse.
const StopWorkerResponse_TypeID = 0xdea9ade321ec73b3

func NewStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func NewRootStopWorkerResponse(s *capnp.Segment) (StopWorkerResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return StopWorkerResponse(st), err
}

func ReadRootStopWorkerResponse(msg *capnp.Message) (StopWorkerResponse, error) {
	root, err := msg.Root()
	return StopWorkerResponse(root.Struct()), err
}

func (s StopWorkerResponse) String() string {
	str, _ := text.Marshal(0xdea9ade321ec73b3, capnp.Struct(s))
	return str
}

func (s StopWorkerResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (StopWorkerResponse) DecodeFromPtr(p capnp.Ptr) StopWorkerResponse {
	return StopWorkerResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s StopWorkerResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s StopWorkerResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s StopWorkerResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s StopWorkerResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s StopWorkerResponse) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s StopWorkerResponse) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s StopWorkerResponse) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s StopWorkerResponse) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// StopWorkerResponse_List is a list of StopWorkerResponse.
type StopWorkerResponse_List = capnp.StructList[StopWorkerResponse]

// NewStopWorkerResponse creates a new list of StopWorkerResponse.
func NewStopWorkerResponse_List(s *capnp.Segment, sz int32) (StopWorkerResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[StopWorkerResponse](l), err
}

// StopWorkerResponse_Future is a wrapper for a StopWorkerResponse promised by a client call.
type StopWorkerResponse_Future struct{ *capnp.Future }

func (f StopWorkerResponse_Future) Struct() (StopWorkerResponse, error) {
	p, err := f.Future.Ptr()
	return StopWorkerResponse(p.Struct()), err
}

type UpdateWorkerStatus capnp.Struct

// UpdateWorkerStatus_TypeID is the unique identifier for the type UpdateWorkerStatus.
const UpdateWorkerStatus_TypeID = 0xa62a70011c9fd5df

func NewUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func NewRootUpdateWorkerStatus(s *capnp.Segment) (UpdateWorkerStatus, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return UpdateWorkerStatus(st), err
}

func ReadRootUpdateWorkerStatus(msg *capnp.Message) (UpdateWorkerStatus, error) {
	root, err := msg.Root()
	return UpdateWorkerStatus(root.Struct()), err
}

func (s UpdateWorkerStatus) String() string {
	str, _ := text.Marshal(0xa62a70011c9fd5df, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStatus) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStatus) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStatus {
	return UpdateWorkerStatus(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStatus) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStatus) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStatus) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStatus) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStatus) Status() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s UpdateWorkerStatus) SetStatus(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s UpdateWorkerStatus) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateWorkerStatus) HasError() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStatus) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateWorkerStatus) SetError(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// UpdateWorkerStatus_List is a list of UpdateWorkerStatus.
type UpdateWorkerStatus_List = capnp.StructList[UpdateWorkerStatus]

// NewUpdateWorkerStatus creates a new list of UpdateWorkerStatus.
func NewUpdateWorkerStatus_List(s *capnp.Segment, sz int32) (UpdateWorkerStatus_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStatus](l), err
}

// UpdateWorkerStatus_Future is a wrapper for a UpdateWorkerStatus promised by a client call.
type UpdateWorkerStatus_Future struct{ *capnp.Future }

func (f UpdateWorkerStatus_Future) Struct() (UpdateWorkerStatus, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStatus(p.Struct()), err
}

type UpdateWorkerStdio capnp.Struct

// UpdateWorkerStdio_TypeID is the unique identifier for the type UpdateWorkerStdio.
const UpdateWorkerStdio_TypeID = 0xa76a3a9604a9e962

func NewUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func NewRootUpdateWorkerStdio(s *capnp.Segment) (UpdateWorkerStdio, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return UpdateWorkerStdio(st), err
}

func ReadRootUpdateWorkerStdio(msg *capnp.Message) (UpdateWorkerStdio, error) {
	root, err := msg.Root()
	return UpdateWorkerStdio(root.Struct()), err
}

func (s UpdateWorkerStdio) String() string {
	str, _ := text.Marshal(0xa76a3a9604a9e962, capnp.Struct(s))
	return str
}

func (s UpdateWorkerStdio) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateWorkerStdio) DecodeFromPtr(p capnp.Ptr) UpdateWorkerStdio {
	return UpdateWorkerStdio(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateWorkerStdio) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateWorkerStdio) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateWorkerStdio) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateWorkerStdio) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateWorkerStdio) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s UpdateWorkerStdio) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateWorkerStdio) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// UpdateWorkerStdio_List is a list of UpdateWorkerStdio.
type UpdateWorkerStdio_List = capnp.StructList[UpdateWorkerStdio]

// NewUpdateWorkerStdio creates a new list of UpdateWorkerStdio.
func NewUpdateWorkerStdio_List(s *capnp.Segment, sz int32) (UpdateWorkerStdio_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[UpdateWorkerStdio](l), err
}

// UpdateWorkerStdio_Future is a wrapper for a UpdateWorkerStdio promised by a client call.
type UpdateWorkerStdio_Future struct{ *capnp.Future }

func (f UpdateWorkerStdio_Future) Struct() (UpdateWorkerStdio, error) {
	p, err := f.Future.Ptr()
	return UpdateWorkerStdio(p.Struct()), err
}

type UpdateClientInfo capnp.Struct

// UpdateClientInfo_TypeID is the unique identifier for the type UpdateClientInfo.
const UpdateClientInfo_TypeID = 0xa073b10fb899cbb0

func NewUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func NewRootUpdateClientInfo(s *capnp.Segment) (UpdateClientInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return UpdateClientInfo(st), err
}

func ReadRootUpdateClientInfo(msg *capnp.Message) (UpdateClientInfo, error) {
	root, err := msg.Root()
	return UpdateClientInfo(root.Struct()), err
}

func (s UpdateClientInfo) String() string {
	str, _ := text.Marshal(0xa073b10fb899cbb0, capnp.Struct(s))
	return str
}

func (s UpdateClientInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (UpdateClientInfo) DecodeFromPtr(p capnp.Ptr) UpdateClientInfo {
	return UpdateClientInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s UpdateClientInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s UpdateClientInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s UpdateClientInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s UpdateClientInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s UpdateClientInfo) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s UpdateClientInfo) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s UpdateClientInfo) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s UpdateClientInfo) Hostname() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s UpdateClientInfo) HasHostname() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s UpdateClientInfo) HostnameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetHostname(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s UpdateClientInfo) System() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s UpdateClientInfo) HasSystem() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s UpdateClientInfo) SystemBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetSystem(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s UpdateClientInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s UpdateClientInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s UpdateClientInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s UpdateClientInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// UpdateClientInfo_List is a list of UpdateClientInfo.
type UpdateClientInfo_List = capnp.StructList[UpdateClientInfo]

// NewUpdateClientInfo creates a new list of UpdateClientInfo.
func NewUpdateClientInfo_List(s *capnp.Segment, sz int32) (UpdateClientInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[UpdateClientInfo](l), err
}

// UpdateClientInfo_Future is a wrapper for a UpdateClientInfo promised by a client call.
type UpdateClientInfo_Future struct{ *capnp.Future }

func (f UpdateClientInfo_Future) Struct() (UpdateClientInfo, error) {
	p, err := f.Future.Ptr()
	return UpdateClientInfo(p.Struct()), err
}

type Message capnp.Struct
type Message_content Message
type Message_content_Which uint16

const (
	Message_content_Which_startWorkerRequest  Message_content_Which = 0
	Message_content_Which_startWorkerResponse Message_content_Which = 1
	Message_content_Which_stopWorkerRequest   Message_content_Which = 2
	Message_content_Which_stopWorkerResponse  Message_content_Which = 3
	Message_content_Which_updateWorkerStatus  Message_content_Which = 4
	Message_content_Which_updateWorkerStdio   Message_content_Which = 5
	Message_content_Which_updateClientInfo    Message_content_Which = 6
)

func (w Message_content_Which) String() string {
	const s = "startWorkerRequeststartWorkerResponsestopWorkerRequeststopWorkerResponseupdateWorkerStatusupdateWorkerStdioupdateClientInfo"
	switch w {
	case Message_content_Which_startWorkerRequest:
		return s[0:18]
	case Message_content_Which_startWorkerResponse:
		return s[18:37]
	case Message_content_Which_stopWorkerRequest:
		return s[37:54]
	case Message_content_Which_stopWorkerResponse:
		return s[54:72]
	case Message_content_Which_updateWorkerStatus:
		return s[72:90]
	case Message_content_Which_updateWorkerStdio:
		return s[90:107]
	case Message_content_Which_updateClientInfo:
		return s[107:123]

	}
	return "Message_content_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0xd270ea7f372f79cd

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0xd270ea7f372f79cd, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Content() Message_content { return Message_content(s) }

func (s Message_content) Which() Message_content_Which {
	return Message_content_Which(capnp.Struct(s).Uint16(0))
}
func (s Message_content) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message_content) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message_content) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message_content) StartWorkerRequest() (StartWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != startWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStartWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerRequest(v StartWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerRequest sets the startWorkerRequest field to a newly
// allocated StartWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerRequest() (StartWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewStartWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StartWorkerResponse() (StartWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != startWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StartWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStartWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStartWorkerResponse(v StartWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStartWorkerResponse sets the startWorkerResponse field to a newly
// allocated StartWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStartWorkerResponse() (StartWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewStartWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StartWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerRequest() (StopWorkerRequest, error) {
	if capnp.Struct(s).Uint16(0) != 2 {
		panic("Which() != stopWorkerRequest")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerRequest(p.Struct()), err
}

func (s Message_content) HasStopWorkerRequest() bool {
	if capnp.Struct(s).Uint16(0) != 2 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerRequest(v StopWorkerRequest) error {
	capnp.Struct(s).SetUint16(0, 2)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerRequest sets the stopWorkerRequest field to a newly
// allocated StopWorkerRequest struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerRequest() (StopWorkerRequest, error) {
	capnp.Struct(s).SetUint16(0, 2)
	ss, err := NewStopWorkerRequest(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) StopWorkerResponse() (StopWorkerResponse, error) {
	if capnp.Struct(s).Uint16(0) != 3 {
		panic("Which() != stopWorkerResponse")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return StopWorkerResponse(p.Struct()), err
}

func (s Message_content) HasStopWorkerResponse() bool {
	if capnp.Struct(s).Uint16(0) != 3 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetStopWorkerResponse(v StopWorkerResponse) error {
	capnp.Struct(s).SetUint16(0, 3)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewStopWorkerResponse sets the stopWorkerResponse field to a newly
// allocated StopWorkerResponse struct, preferring placement in s's segment.
func (s Message_content) NewStopWorkerResponse() (StopWorkerResponse, error) {
	capnp.Struct(s).SetUint16(0, 3)
	ss, err := NewStopWorkerResponse(capnp.Struct(s).Segment())
	if err != nil {
		return StopWorkerResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStatus() (UpdateWorkerStatus, error) {
	if capnp.Struct(s).Uint16(0) != 4 {
		panic("Which() != updateWorkerStatus")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStatus(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStatus() bool {
	if capnp.Struct(s).Uint16(0) != 4 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStatus(v UpdateWorkerStatus) error {
	capnp.Struct(s).SetUint16(0, 4)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStatus sets the updateWorkerStatus field to a newly
// allocated UpdateWorkerStatus struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStatus() (UpdateWorkerStatus, error) {
	capnp.Struct(s).SetUint16(0, 4)
	ss, err := NewUpdateWorkerStatus(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStatus{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateWorkerStdio() (UpdateWorkerStdio, error) {
	if capnp.Struct(s).Uint16(0) != 5 {
		panic("Which() != updateWorkerStdio")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateWorkerStdio(p.Struct()), err
}

func (s Message_content) HasUpdateWorkerStdio() bool {
	if capnp.Struct(s).Uint16(0) != 5 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateWorkerStdio(v UpdateWorkerStdio) error {
	capnp.Struct(s).SetUint16(0, 5)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateWorkerStdio sets the updateWorkerStdio field to a newly
// allocated UpdateWorkerStdio struct, preferring placement in s's segment.
func (s Message_content) NewUpdateWorkerStdio() (UpdateWorkerStdio, error) {
	capnp.Struct(s).SetUint16(0, 5)
	ss, err := NewUpdateWorkerStdio(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateWorkerStdio{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message_content) UpdateClientInfo() (UpdateClientInfo, error) {
	if capnp.Struct(s).Uint16(0) != 6 {
		panic("Which() != updateClientInfo")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return UpdateClientInfo(p.Struct()), err
}

func (s Message_content) HasUpdateClientInfo() bool {
	if capnp.Struct(s).Uint16(0) != 6 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message_content) SetUpdateClientInfo(v UpdateClientInfo) error {
	capnp.Struct(s).SetUint16(0, 6)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewUpdateClientInfo sets the updateClientInfo field to a newly
// allocated UpdateClientInfo struct, preferring placement in s's segment.
func (s Message_content) NewUpdateClientInfo() (UpdateClientInfo, error) {
	capnp.Struct(s).SetUint16(0, 6)
	ss, err := NewUpdateClientInfo(capnp.Struct(s).Segment())
	if err != nil {
		return UpdateClientInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Content() Message_content_Future { return Message_content_Future{p.Future} }

// Message_content_Future is a wrapper for a Message_content promised by a client call.
type Message_content_Future struct{ *capnp.Future }

func (f Message_content_Future) Struct() (Message_content, error) {
	p, err := f.Future.Ptr()
	return Message_content(p.Struct()), err
}
func (p Message_content_Future) StartWorkerRequest() StartWorkerRequest_Future {
	return StartWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StartWorkerResponse() StartWorkerResponse_Future {
	return StartWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerRequest() StopWorkerRequest_Future {
	return StopWorkerRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) StopWorkerResponse() StopWorkerResponse_Future {
	return StopWorkerResponse_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStatus() UpdateWorkerStatus_Future {
	return UpdateWorkerStatus_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateWorkerStdio() UpdateWorkerStdio_Future {
	return UpdateWorkerStdio_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_content_Future) UpdateClientInfo() UpdateClientInfo_Future {
	return UpdateClientInfo_Future{Future: p.Future.Field(0, nil)}
}

const schema_dcccaa5d36aa8b70 = "x\xda\xa4\x96kh\x14W\x1b\xc7\x9f\xe7\x9c\xd9\x9d\xdd" +
	"\x97]\x93a\xd6\x17\x04!\xe8\xfb\xbe\xa0\x82\x89\xd7\xb7" +
	"U\x90\x18s\x91XMrv\x93\xc6\x0fMq\xcc\x1e" +
	"\xe3\xd6dv\xdd\x99Q\x83\x85\xd0~\xa9\xa9\xd5\xa2m" +
	"\xbc\x14Q+\xbdh\xa8\xa8\xd4\x82\x82B\xab\xa6Zj" +
	"@m\x85*\xa9\x05K[\x0dmA\xab\x1fL\xb5S" +
	"\xce\xcc\xdew\xab\x96~\xdb9\xfc\xcf\xef\xfc\x9f\xcby" +
	"\xce\xceXD\x17J3\x83\xcd~ \xac\xdb\xe3\xb5\x7f" +
	"Y2\xe7\xe4I\xeb\xc6fP\x02\x92\x9d\xd8<\xf8\xff" +
	"\x8e\xc1\x8b#\x00\xa8n\x91n\xaa\xbb%\x19 \xf2\xb6" +
	"D1\xb2_\"\x08`\x0fl=\xda\xf1\xacg\xee\xb6" +
	"\"\xf9\xbb\xd2\x15\xf5\xb0#?(\xe4\xc7]\xf9\xbc\xa1" +
	"\xf3;\xffs\xd4;P$?&\xddTO;\xf2\x13" +
	"B~\xce\x95/\xadz\xb5\x9f\xbf\xb8bG\x91|H" +
	":\xa3\x0e;\xf2\x0bB\xfe\xb5+\x9f\\\xb5\xb1b\xeb" +
	"\xbc\xb3;\x0b\xe5\xb3\x87$\x82\xeaeG\x7fQ\xe8\xbf" +
	"q\xf5k\xf6\xfc\xf8^%\xdd\xbe\x0b\x94\x00f\xf5\x1e" +
	"*\x03\xa8_Hc\xeaU\xb1C\xbd,\x1d\x01\xb4W" +
	"\xc5:\xf6\xdc\xf1\x7f\xb4\xb7\xc8J\xbf\xe7\x8c\xba\xcd#" +
	"\xd0ox(Fvy\x1c\xf4\xd1/w\x9f(;f" +
	"\xec/@;\xc0~\xcf\xa8: v\xa8\xdb<?\x01" +
	"\xda\xdf]\xdd7\x11\x13\xd3>\x00\x16\xc0\\1\x0aI" +
	"\x8fwL\xed\xf5\x8a_\x96w=\xa0\xbd\xf2\xf6!i" +
	"\xc7\xfc\x97>,\x00;\xda\xcb\xde\xbb\xea\xb7\x8e\xf6\x9a" +
	"\xb7\x1a\xd0>\xf5V\xdc\xdc\xb4\xa0\xe9H\x91\xe7\x07\xde" +
	"\xeb\xaaG\x96\x01\xc22\xc5H@v-\x7fU\xaf\x1f" +
	"\xac{\xe1X>\xd9q\x1c\x94\xef\xaa\x13d\x19\xa8\xad" +
	"\x0c\xb6O8P\xc5\x8f\x03\x0b!\xda\xc3\xbdU\xcf\xf4" +
	"\x8d&\xae@\x1b\xca\x8e\x83\xfb\xde\x9b\x80\xb3\x1fx\xdf" +
	"D@{w\xff\x85\xe9\xb3z\xcf\x9e.:\xfe\xa4\xef" +
	"\xba:\xe4\x13)\xfb\xd4G1r\xd1\xe7\x9c\xbf\xe5\xe0" +
	"\xbe\xdf6J\xf7\x86JD6{\xd8GP\xbd&\xb6" +
	"\xa8W}\"\xb4\xf7O\xed\xdf\xb4w\xf1\xc0\xf9\"\xf6" +
	"}\xdf\xa8\x8a~\xc1~(\xd8>\xbf\xc3\xce\x18-\x95" +
	"\xe2\xa0\xff\x80:^lQ\x15\xbf`7\x8f\xbb\xbd~" +
	"\xc1\x84\xcfG\x8a\xd8\xe3\xfd\xd7\xd5I\x0e{\xa2\x9fb" +
	"d\x8a\xcb\xfe\xd8\xf8y\xd2\xf7\x87\x0f\xdd(U\x91\xa9" +
	"\xfe1u\xae\x83\x9e\xe9\xa0\xff\xbd\xa9\xe1\xb5\xd0++" +
	"\x7f-B3\xff\xa8\xda\xe1\xa0\x97\x0btT\xa0\x97\xd9" +
	"Z\x17\xd7\xcd\xcaN\x8d$\xf4\xc4|\xbe\xce\x8c\x98Z" +
	"\xd2l\x8f'\xd7\xc8<\xd9\xda\x82\x88\x01 \x18\x00\x98" +
	"\x89\x04\xed\x86%\x955\x8b\xeb\x9bZ\xbd\x95\xff3*" +
	"\xeb\x9fo\xadlo\x0e?W\x1f\x16_\x91\xd6\x9ap" +
	"+\xa4i)X\x8d\xf8l\xd4W\xc51\x17\xa5\xe0`" +
	"\x86\x84iRYcSCs\xbe\x9b\xce\x9e\xe8\xd3\xbb" +
	"\xa9]V\xf7x7\x1bbf\x83\x16\xeb\xb6\x92\x1c\x04" +
	"\xc8\x03\x04=(\x92\x9bV\xd1\xb4\xac6\xde\xd3\xa3\xe9" +
	"\xd1\xa6\xb8\xd9\x10\xb7\xf4h\x8e\xbc/G\xeeX\xcc\xf8" +
	"\xe3\xc9p5_kq\xc3lAd\x01*\x01H\x08" +
	"\xa0\xd4/\x02`\x0b)\xb2\xa5\x04\x15\xc4\x908Qi" +
	"\x9c\x06\xc0\xea(\xb2\x15\x04\x15BBH\x00\x94\x8e\xc9" +
	"\x00l9Ef\x12\xec\xebt-\xa4\xc2\xc52-\xd9" +
	"e\xe08\xc0\x16\xea\xa6`\x1c\xa0\xcc\xf5u\x05K\x05" +
	"\xc5\xdc\x103#Vg'7\x8cl\x08\x85\xa2\xb6D" +
	"T3ymw\x8c\xebf\x99\xa8\x94\xb0_\x9e\xb1\xaf" +
	"-\x01`+(\xb2\xee\x1c\xfb1\xb1\xb8\xdau\x9a\xb1" +
	"\xbfv>\x00\xeb\xa6\xc86\x10T(\x0d!\x05P," +
	"\x11}\x82\"{\x99\xa0m\x19<\xa9k=\x1c\x00\xd2" +
	"q\xd9\xab\xe3\x86Y\xb0Vm\xf4\x1a&\xefI\x7f\xf6" +
	"i\xd1h\x92\x1bFfK\x09\xfbn\x01\xaa#\xa6f" +
	"Z\x86\x08\xc0\x97\x09`\xaa\xb0\xf5_\x8al\x06\xc1\xb4" +
	"\xff\xe9\xb3\x00\xd8\x14\x8al\x0e\xc1j\xc3\xd9\x94NN" +
	"\x05O&\xe3\xc9'\x9fU\x111\xa31'WR\xe6" +
	"\xa8\xa0\xa8\xaa\x8f\"\x0b\x11,\x8bj\xa6\x86A \x18" +
	",*\x8b\xb8c\xf1\x84\xc3\xa1\xc9\xfc{1\x96\xe9i" +
	"Rx\xc3\xaaES7\xb7\x14\xb6_\x0a\x94\x0c\xf3\x8a" +
	"t\xf7\xe5K\x96q\xc3\xd0\xbaxeg\\7e\xae" +
	"\x9bl\"\x95\x02\xb6\xed8\xfe\xe4\x1d\x00v\x82\";" +
	"G0\x88\x7f\xd8nz>;\x00\xc0\xceQd\x97\x08" +
	"\x06\xc9#\xdb\xad\xef\xf0v\x00v\x89\"\x1b!\x18\xa4" +
	"\x0fm\xb7\xc0\xd7\x04a\x84\"\xbbE0(\xfdn\x87" +
	"P\x02P~\x10\xab\xb7(\xb2{\x04\x83\x9e1;\x84" +
	"\x1e\x00\xe5\x8e \xdc\xa3\x18F\x82A\xef\x03;\x84^" +
	"\x00\xe5\xd1\xeb\x00a\x14O\x84\xb8\xd2F\xea>\xa1\x13" +
	"\xd2Z\x8bS\xc3\xc4\xf2\xec+\x0a\x88\xe5P(3\x12" +
	"qY78\x96g\xe7{F\xe7\xe6\x07S4\x03\x05" +
	"-\xf3\x0a\x95R\x19\x89\xb8N\x1dXf\xe8\xa6dV" +
	"\xaa\xfe(\xf2-z\x8dZ\x06\x96g\x9f\xd6\xd2\xb2h" +
	"\x0c\xe3X\x9e}S\xf3T\xb5\xdd\x18KMH\x00\xe1" +
	",\xfd\xa4\xa7T\x85\xe3\xb0=\x193\xb9`R\xfd/" +
	"\xa7\xa1\\j\x1a\xd656\xe5M\xc3\xdc\xb9\xe5\x84l" +
	"8S1\xb7\x9bge\xbb\xf9q\xb7\x82\xafKq\"" +
	"f\xb4,n\x99\xf9\xbe\xfe\x95\xf5EK\xbd\x19u\xcd" +
	"m\xad93\x15\xd3\x1d+k]<\xe3\x071\xfb\x9f" +
	"@\x09.\x02\xd2'\x9a\x99\xebf\x89\xe7\xe2\xe9.V" +
	"nz\x9ex\xb1\xaa\xdd\xfc\xfc\xe3\xf4he\xa6e\xfc" +
	"\xbd\xf4\xd4\xb4\xb6E\x00\xfe\x0c\x00\x00\xff\xff\xe1\xcc)" +
	"\xf5"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_dcccaa5d36aa8b70,
		Nodes: []uint64{
			0x8bde75b9b9344aed,
			0x913505385db08e95,
			0x9506b02397c7c539,
			0x96605e6589822f4c,
			0x97c3398e1f7b2f22,
			0x9892032ea4e69c6b,
			0x9eac09f19c5d6966,
			0xa073b10fb899cbb0,
			0xa62a70011c9fd5df,
			0xa76a3a9604a9e962,
			0xaf4e3d88746f93bc,
			0xb15c44a86e45d3b0,
			0xb4652fa21957aa11,
			0xbdc379322dc88999,
			0xc5f4047bf39fa88d,
			0xc795479e88a0bca5,
			0xd270ea7f372f79cd,
			0xdcc6193d77e90e4f,
			0xdea9ade321ec73b3,
			0xee62811487468816,
		},
		Compressed: true,
	})
}
